openvm-org/openvm

- benchmarks/README.md
- book/src/advanced-usage/sdk.md
- crates/toolchain/tests/README.md
- docs/crates/benchmarks.md
- docs/specs/ISA.md
- extensions/keccak256/circuit/README.md
Fix typo and invalid links
I'v been checked every ‘md’ files in the repository and found some invalid links and typo.
I fixed most of the invalid links, but https://github.com/openvm-org/openvm/issues/1110#issue-274550834 thought it was better to open an issue rather than fix them arbitrarily.
I also found a minor typo and fixed it, otherwise the documentation looks perfect. Hope this helps.
> docs: cleanup documents

- benchmarks/src/utils.rs
- book/src/writing-apps/build.md
- crates/cli/src/commands/build.rs
- crates/sdk/src/lib.rs
- crates/toolchain/build/src/lib.rs
- crates/toolchain/tests/src/utils.rs
In order to fix it, the signature was also changed. Now `cargo build`
- Doesn't have the `--name` flag,
- Has either `--bin <name>` or `--example <name>` flags (as opposed to previous `--bin` and `--name`),
- Cannot filter just by name,
- `--bin <name>` looks for packages with name _exactly_ `<name>`, as opposed to previous behaviour where it was looking for packages with substring `<name>` (similar to how `cargo test` works); the same about `--example <name>`.
---
Copilot:
This pull request introduces significant changes to the build process and command-line interface (CLI) for building guest packages. The main focus is on enhancing the flexibility of target filtering and improving the handling of example targets.
* [`crates/cli/src/commands/build.rs`](diffhunk://#diff-5cf96c1ea2590929023 …
> [fix] `build_guest_package` didn't target any specific package, there was no way to build examples with it

- Cargo.lock
- Cargo.toml
I had ran all tests and benchmarks in #1100 because just `Cargo.toml` change cannot trigger CI. All tests are passed and benchmarks are same.
> [update] Update openvm-stark-backend to v0.1.1-alpha

- benchmarks/benches/fibonacci_execute.rs
This wasn't updated after some changes because it's not run in CI.
> chore: fix fibonacci runtime bench

- .github/workflows/docs.yml
- .github/workflows/ecc.yml
- .github/workflows/lints.yml
- Cargo.lock
- Cargo.toml
- extensions/pairing/guest/Cargo.toml
- extensions/pairing/guest/src/bls12_381/tests.rs
- extensions/pairing/guest/src/bn254/mod.rs
- extensions/pairing/guest/src/bn254/tests.rs
- extensions/pairing/guest/src/halo2curves_shims/bls12_381/mod.rs
- extensions/pairing/guest/src/halo2curves_shims/bls12_381/tests/mod.rs
- extensions/pairing/guest/src/halo2curves_shims/bls12_381/tests/test_miller_loop.rs
- extensions/pairing/guest/src/halo2curves_shims/bn254/mod.rs
- extensions/pairing/guest/src/halo2curves_shims/bn254/tests/mod.rs
- extensions/pairing/guest/src/halo2curves_shims/bn254/tests/test_miller_loop.rs
Not sure why CI fails, something about halo2curves
> chore: add doc check to lint

- book/src/advanced-usage/sdk.md
Hi, 
I was playing with the vm, and following the book, I realized that the fix 4250ce882f1290902de163efd279330c87ba163f did not updated the documentation for the sdk.
I leave here the repo to the sdk working example: https://github.com/openvm-org/openvm-example-fibonacci
> book: sdk usage correction

- .github/workflows/lints.yml
- benchmarks/programs/base64_json/src/lib.rs
- benchmarks/programs/base64_json/src/main.rs
- benchmarks/programs/bincode/src/main.rs
- examples/algebra/Cargo.toml
- examples/algebra/src/main.rs
- examples/i256/src/main.rs
- examples/keccak/src/main.rs
- examples/u256/src/main.rs
- extensions/bigint/tests/programs/examples/book-example2.rs
- extensions/bigint/tests/programs/examples/matrix-power-signed.rs
- extensions/bigint/tests/programs/examples/matrix-power-unsigned.rs
- extensions/ecc/tests/programs/examples/ec.rs
- extensions/ecc/tests/programs/examples/ecdsa.rs
- extensions/keccak256/tests/programs/examples/keccak.rs
- extensions/pairing/tests/programs/examples/fp12_mul.rs
- extensions/pairing/tests/programs/examples/pairing_check.rs
- extensions/rv32im/tests/programs/examples/read.rs
target to resolve #1125 
q. cannot find `**/test/programs` so had with `examples/*`
> fix: lints to guest programs

- benchmarks/src/utils.rs
- book/src/writing-apps/build.md
- crates/cli/example/Cargo.toml
- crates/cli/src/commands/build.rs
- crates/toolchain/build/src/config.rs
- crates/toolchain/build/src/lib.rs
- crates/toolchain/tests/src/lib.rs
Closes https://github.com/openvm-org/openvm/issues/1141
Test also uncovered that the output target directory should be "debug" when profile is "dev".
> fix: cli build with profile

- Cargo.lock
- benchmarks/src/bin/fib_e2e.rs
- benchmarks/src/bin/verify_fibair.rs
- crates/cli/src/commands/keygen.rs
- crates/sdk/Cargo.toml
- crates/sdk/examples/sdk.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/app.rs
- crates/sdk/src/prover/mod.rs
- crates/sdk/src/prover/stark.rs
- crates/sdk/src/prover/vm/local.rs
Cleanup benchmark so verify_fibair actually uses volatile memory (it should not have continuations enabled).
In the process:
- rename `get_vk` to `get_app_vk`
- add non-continuation prove and verify functions to `AppProver`
- remove `profiling` flag from sdk provers: this should just be set in the VmConfig and we do not encourage rerunning execution twice
In this PR, the Fibonacci STARK number of rows is kept the same. In a future PR I may increase the number of rows in the to-be-verified STARK to make the benchmark bigger.
> fix(bench): verify_fibair use volatile memory

- benchmarks/README.md
- benchmarks/src/bin/ecrecover.rs
- benchmarks/src/utils.rs
- crates/circuits/sha256-air/src/trace.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/root.rs
- crates/sdk/src/prover/vm/local.rs
- docs/crates/metrics.md
towards INT-2940
Change `DEFAULT_NUM_CHILDREN_LEAF=1` because I think the App VM is usually very wide and its better to do a 1-1 aggregation first to get to a Agg VM proof. This is configurable from the `AggConfig`.
Update the metric labels a little so that `group` scopes based on the aggregation layer.
> chore: leaf aggregation tuning

- extensions/native/compiler/src/conversion/mod.rs
> chore: change address space in native compiler

- .github/workflows/benchmarks.yml
- .github/workflows/toolchain-native.yml
- docs/specs/ISA.md
- extensions/native/circuit/src/adapters/loadstore_native_adapter.rs
- extensions/native/circuit/src/loadstore/core.rs
- extensions/native/circuit/src/loadstore/tests.rs
- extensions/native/compiler/src/asm/compiler.rs
- extensions/native/compiler/src/asm/instruction.rs
- extensions/native/compiler/src/conversion/mod.rs
- extensions/native/compiler/src/lib.rs
> feat: remove LOADW2 and STOREW2

- benchmarks/benches/regex_execute.rs
- benchmarks/examples/regex_execute.rs
- crates/vm/src/metrics/mod.rs
A stupid but important performance optimization when metric collection is turned on: every instruction increments the cycle count. When this is done directly via `metric::Counter` the metric recorder acquires a lock every time. This has significant (2x) performance impact on execution.
> perf: lock-free cycle count increment

- book/src/custom-extensions/bigint.md
- book/src/custom-extensions/ecc.md
- book/src/custom-extensions/keccak.md
Hi! I’ve fixed some broken links in the documentation for the `bigint`, `ecc`, and `keccak` extensions. The updated links now point to the correct paths within the repository.
> fix: broken links

- .github/workflows/benchmark-call.yml
- benchmarks/src/bin/fib_e2e.rs
- benchmarks/src/utils.rs
- ci/scripts/bench.py
- extensions/native/recursion/src/halo2/utils.rs
add `--kzg-params-dir` to benchmark cli args to specify the kzg trusted setup directory.
workflow: https://github.com/openvm-org/openvm/actions/runs/12645324202/job/35234301358
> fix(ci): benchmark-e2e params dir

- crates/toolchain/instructions/src/program.rs
- crates/vm/src/system/program/mod.rs
- crates/vm/src/system/program/tests/mod.rs
- crates/vm/src/system/program/trace.rs
Adds a `ProgramChip` test with a program that has `None` instructions. Fixes trace generation to pass this test: previously, the frequencies array was just directly being converted into the trace, even though the cached trace skipped the instructions that were `None`. Now those are skipped in trace generation for the frequencies as well.
Adds a constructor for `Program` that takes in a `Vec` of `Option<Instruction>`. Also changed the name of `Program::instructions()` to `Program::non_none_instructions` since the old name seemed misleading, and added `Program::num_non_none_instructions()` since that was the only use of `Program::instructions()` other than for display. These names don't seem very good so someone should suggest better ones.
> Fix: Ensure program trace for frequencies skips `None` instructions

- book/src/advanced-usage/sdk.md
This pull request fixes a typo in the `sdk.md` file. The word **appropraite** was corrected to **appropriate**.
> ...get the appropraite KZG params by running the following command.
> ...get the appropriate KZG params by running the following command.
- Corrected the typo on line 77 of `book/src/advanced-usage/sdk.md`.
---
Let me know if further edits are needed. Thank you!
> fix typo Update sdk.md

- docs/repo/layout.md
Fix typo in `layout.md`
This pull request addresses a typo in the `layout.md` file:
- Corrected "simultaenously" to "simultaneously."
Thank you for reviewing this small change!
> fix typo Update layout.md

- extensions/native/circuit/src/castf/core.rs
- extensions/rv32im/circuit/src/adapters/hintstore.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/jalr/core.rs
- extensions/rv32im/circuit/src/shift/core.rs
Decreases execute time by ~4%.
closes INT-2528
> perf: Move range checks to trace gen

- .github/workflows/extension-tests.yml
- extensions/algebra/circuit/src/fp2_chip/addsub.rs
- extensions/algebra/circuit/src/fp2_chip/muldiv.rs
- extensions/algebra/moduli-setup/src/lib.rs
- extensions/algebra/tests/programs/examples/complex-secp256k1.rs
- extensions/algebra/tests/programs/examples/complex-two-modulos.rs
@luffykai the modular (fp not fp2) tests weren't failing because they don't seem to use exprbuilder in the same way. Can you fix it?
> fix(test): add setup instruction to fp2 tests

- extensions/native/recursion/src/stark/mod.rs
From ininitial implementation of verifier that did not handle RAP phases
> chore: Remove old FIXME

- extensions/native/circuit/src/castf/core.rs
- extensions/native/circuit/src/castf/tests.rs
Fixes the bug below.  The root cause was that the range check interaction in CASTF did not condition the send on row validity.
```
$ cargo test --package openvm-native-circuit --lib -- castf::tests::castf_rand_test --exact --show-output
running 1 test
test castf::tests::castf_rand_test ... FAILED
successes:
successes:
failures:
---- castf::tests::castf_rand_test stdout ----
Bus 4 failed to balance the multiplicities for fields=[0, 8]. The bus connections for this were:
Air idx: 2, Air name: VmAirWrapper<ConvertAdapterAir<1, 4>, CastFCoreAir>, interaction type: Send, count: 1
Air idx: 2, Air name: VmAirWrapper<ConvertAdapterAir<1, 4>, CastFCoreAir>, interaction type: Send, count: 1
Air idx: 2, Air name: VmAirWrapper<ConvertAdapterAir<1, 4>, CastFCoreAir>, interaction type: Send, count: 1 …
```
> fix(castf): handle range check correctly for padding rows

- crates/vm/tests/integration_test.rs
- docs/specs/ISA.md
- docs/specs/RISCV.md
- extensions/native/circuit/src/adapters/loadstore_native_adapter.rs
- extensions/native/circuit/src/extension.rs
- extensions/native/circuit/src/loadstore/core.rs
- extensions/native/circuit/src/loadstore/tests.rs
- extensions/native/compiler/src/asm/compiler.rs
- extensions/native/compiler/src/asm/instruction.rs
- extensions/native/compiler/src/conversion/mod.rs
- extensions/native/compiler/src/lib.rs
- Adds vectorized native load / store / hint chip.  
- Renames SHINTW to HINT_STOREW for consistency.
- Adds LOADW4, STOREW4, HINT_STOREW4 opcodes and uses them for Ext.
- Updates ISA docs to be consistent.
Closes INT-2941, INT-2620, INT-2621.
> feat: vectorize native load store 

- extensions/bigint/guest/src/externs.rs
@arayikhalatyan can you help add some unit tests for extern functions in this repo for the future?
> fix: bigint extern functions were not updated on macro usage

- crates/circuits/mod-builder/src/README.md
This pull request fixes a minor typo in the `README.md` file:
- Corrected "impelementation" to "implementation" for better clarity and professionalism.
> chore: fix typo README.md

- extensions/native/circuit/src/adapters/loadstore_native_adapter.rs
- extensions/native/circuit/src/extension.rs
- extensions/native/circuit/src/loadstore/core.rs
- extensions/native/compiler/src/conversion/mod.rs
- extensions/native/compiler/src/lib.rs
> chore: make handling of LOADW4 / STOREW4 / HINT_STOREW4 uniform

- extensions/ecc/circuit/src/config.rs
- extensions/ecc/circuit/src/weierstrass_chip/double.rs
- extensions/ecc/tests/programs/Cargo.toml
- extensions/ecc/tests/programs/examples/ec.rs
- extensions/ecc/tests/programs/examples/ec_two_curves.rs
- extensions/ecc/tests/src/lib.rs
WeierstrassConfig (only used for testing) auto creates the moduli. It is more natural to do `coordinate,scalar` per curve instead of doing all coordinate first.
> fix: WeierstrassConfig zip moduli

- extensions/native/recursion/src/fri/domain.rs
- extensions/native/recursion/src/utils.rs
These places don't really need changes. The comments just note that we should be careful.
closes INT-3019
closes INT-3021
> [doc] Remove unnecessary FIXME

- extensions/native/compiler/src/asm/compiler.rs
- extensions/native/compiler/src/ir/bits.rs
- extensions/native/compiler/src/ir/instructions.rs
- extensions/native/compiler/tests/hint.rs
- extensions/native/recursion/src/halo2/tests/mod.rs
Closes INT-3017
Before: https://github.com/openvm-org/openvm/blob/benchmark-results/benchmarks-dispatch/refs/heads/main/summary.md
After: https://github.com/openvm-org/openvm/blob/benchmark-results/benchmarks-dispatch/refs/heads/chore/cleanup-num2bits/summary.md
Small performance regression: ~50K additional cells, ~2K additional cycles for the leaf proof.
> chore: cleanup num2bits

- crates/circuits/mod-builder/src/builder.rs
We revert to enforcing at the program code level that:
- a valid program must call the correct setup opcodes to be correct
It would be better if we can constraint this in the circuit, however this has the challenge that when the same chip is used across continuation segments, only the first segment will have setup called.
> fix: remove setup on first row constraint

- extensions/ecc/circuit/src/weierstrass_chip/double.rs
We need the dummy row to have `is_valid=0, is_double=0`. Previously we did this by duplicating the first row. However when the same chip is used across continuation segments, the first row might not be setup. So now we explicitly generate the dummy row to have the above properties.
> fix: EcDoubleChip dummy row

- .github/workflows/benchmarks.yml
- Cargo.lock
- benchmarks/src/utils.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/bin/app_prover.rs
- crates/sdk/src/bin/program_executor.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
ref INT-3046
ref INT-3001
the binary is just skeleton, @Jocn2020 will take over
> [chore] sdk refactor: separate leaf running + scheduling

- extensions/native/compiler/src/ir/builder.rs
- extensions/native/compiler/src/ir/symbolic.rs
- extensions/native/recursion/src/fri/two_adic_pcs.rs
- `alpha_pow` is only computed once for each matrix.
- Let's say `w_i` is the width of i-th matrix. Before we have `max(w_i)` multiplication for `alpha_pow` and now we only need `sum(log(w_i))`. 
- `range_with_step` and `step_sizes` are added for a reverted change. It's not necessary but good to have. 
- Fixed a bug in `for_each_unrolled`.
- Based on metrics, we might revert the change on the static verifier part.
> [chore] Optimize `alpha_pow` computation

- extensions/pairing/guest/src/bls12_381/mod.rs
- extensions/pairing/guest/src/bls12_381/pairing.rs
- extensions/pairing/guest/src/bls12_381/tests.rs
- extensions/pairing/guest/src/bls12_381/utils.rs
- extensions/pairing/guest/src/bn254/mod.rs
- extensions/pairing/guest/src/bn254/pairing.rs
- extensions/pairing/guest/src/bn254/tests.rs
- extensions/pairing/guest/src/bn254/utils.rs
- Adds pairing check hint for BN254 and BLS12-381 using halo2curves_shims
- Adds test for pairing check hint
- Moves conversion functions into utils.rs file
Towards INT-2963
> feat: Pairing check hint for target_os != zkvm

- extensions/native/compiler/src/constraints/halo2/baby_bear.rs
- extensions/native/compiler/src/constraints/halo2/compiler.rs
- extensions/native/compiler/src/ir/instructions.rs
- extensions/native/compiler/src/ir/utils.rs
- extensions/native/recursion/src/fri/two_adic_pcs.rs
> [chore] Optimize Static Verifier alpha pow computation

- crates/vm/src/arch/config.rs
- crates/vm/src/arch/segment.rs
> [feat] support custom segmentation

- crates/vm/src/arch/vm.rs
> [feat] support execute until segment

- extensions/algebra/moduli-setup/src/lib.rs
Currently, if the modulus has 40 bytes, the blocksize is 8 and final number of limbs is still 40.
But we can't really do 40, as the adapter is either 32 or 48. Change the macro to match that logic
> [fix] modular setup macro padding

- .github/workflows/cli.yml
Currently, the CI workflow for testing examples (the `app-level-cli` job) just built every example with `cargo openvm build` but this change makes it run as well with `cargo openvm build && cargo openvm run`
> Add `cargo openvm run` to the app-level-cli CI job

- crates/vm/src/arch/vm.rs
redo #1254 
the fix is in second commit (I double-take the streams) -> we do have test with continuation, but not actually using input
fix INT-3004
> [fix] support execute until segment 

- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/mod.rs
- crates/sdk/src/prover/stark.rs
redo https://github.com/openvm-org/openvm/pull/1243
> [chore] expose root verifier input

- crates/vm/derive/src/lib.rs
- crates/vm/src/arch/extensions.rs
- extensions/rv32im/circuit/src/extension.rs
Implements the following:
- `VmConfig` macro implements config inheritance (via the `#[config]` attribute in place of `#[system]`)
- `Rv32ImConfig` inherits `base` and `io` from `Rv32IConfig`
- `impl VmExtension` for the option of an arbitrary `VmExtension`
> feat: config inheritance in the VmConfig derive macro

- crates/sdk/src/fs.rs
pub function probably shouldn't mention bitcode. in case we need to switch it
> [chore] update sdk fs api

- extensions/native/compiler/src/constraints/halo2/baby_bear.rs
Babybear now uses gate.inner_product() to save on a few cells for ext multiply (which is called a lot). Seems to give 10% decrease in cells for this test: halo2::tests::stark::test_fibonacci
> change to inner product

- Cargo.lock
- crates/cli/src/commands/verify.rs
- crates/sdk/examples/sdk_evm.rs
- crates/sdk/src/lib.rs
- crates/sdk/tests/integration_test.rs
- extensions/native/recursion/src/halo2/wrapper.rs
Following up after https://github.com/axiom-crypto/snark-verifier/pull/69
> `Sdk::verify_evm_proof` fallible

- crates/circuits/primitives/src/README.md
- crates/circuits/primitives/src/range/README.md
- crates/circuits/primitives/src/range_gate/README.md
- crates/circuits/primitives/src/var_range/README.md
- crates/circuits/primitives/src/xor/README.md
- Added a README for `circuits/primitives`, which includes links to each circuit in the directory.
- Specifically added README for `range_check`, `range_gate`, and `xor`.
- For the SubAir primitives, I linked directly to mod.rs, as it already contains detailed inline comments.
Closes INT-3090
> [docs] Add contributor documentations for circuit primitives

- extensions/keccak256/circuit/src/air.rs
- extensions/keccak256/circuit/src/columns.rs
- extensions/keccak256/circuit/src/trace.rs
for safety to prevent keccak from being able to write to address space 0 or 1.
towards INT-3123
> chore: fix keccak address space `e = 2`

- crates/vm/src/arch/testing/memory/mod.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/offline.rs
- crates/vm/src/system/memory/tests.rs
- extensions/keccak256/circuit/src/trace.rs
- extensions/native/circuit/src/fri/mod.rs
- extensions/native/circuit/src/poseidon2/trace.rs
- extensions/rv32-adapters/src/eq_mod.rs
- extensions/rv32-adapters/src/heap_branch.rs
- extensions/rv32-adapters/src/vec_heap.rs
- extensions/rv32-adapters/src/vec_heap_two_reads.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/sha256/circuit/src/sha256_chip/trace.rs
This allows us to change out the implementation (e.g., SmallVec) without affecting the interface
> chore: Remove Vec from MemoryRecord interface

- crates/vm/src/arch/segment.rs
- crates/vm/tests/integration_test.rs
Some tests relied on now-invalid behavior from the native extension and have been removed.
> fix: update integration tests for new native address space restrictions

- extensions/native/recursion/src/fri/two_adic_pcs.rs
> chore: update comment on MAX_LOG_WIDTH

- crates/prof/src/aggregate.rs
- crates/prof/src/main.rs
- crates/prof/src/types.rs
Too many metrics in one benchmark is hard for bencher to manage
> chore(prof): split benchmark output into separate benchmarks by group

- crates/vm/src/system/memory/controller/interface.rs
- crates/vm/src/system/memory/volatile/mod.rs
VolatileMemory does not need to internally maintain touched addresses as it is given `final_memory` in `finalize`. This does mean that `current_trace_height` is no longer known until finalization.
> perf: Remove touch address for VolatileMemory

- crates/vm/src/system/memory/controller/interface.rs
- crates/vm/src/system/memory/merkle/mod.rs
- crates/vm/src/system/memory/merkle/tests/mod.rs
- crates/vm/src/system/memory/persistent.rs
Previously `touch_range` was implemented by calling `touch_address` on each address in `pointer..pointer + len`. But for persistent memory, in both `MemoryMerkleChip` and `PersistentBoundaryChip`, we actually care about touched aligned blocks of size 8. So most of the triggered calls to `touch_address` via a single `touch_range` were redundant, repeatedly querying the same hashmap at the same block index.
> perf: More efficient touch_range

- crates/vm/src/system/memory/offline.rs
**Metric:** tracegen
**Before:** 21246 ms
**After:** 19288 ms
**Percentage gain:** -9.2%
Source: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13120710102
---
This resolves INT-3235.
_Quote from the ticket._
Currently one actual block corresponds to several memory addresses. Whenever we modify the block itself (e.g. change the timestamp), we have to change it for every memory address it covers.
We could instead store the blocks we constructed in a separate storage (Vec), and in the positions we will store a simple usize denoting the block index in the storage. This also kind of simplifies the concept of the "default" block (we assign 0 to be a fictious index meaning "not initialized yet"), and generally makes the block data memory take less space and probably makes …
> [perf] Store blocks in a potentially smarter way

- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/tree/mod.rs
- crates/vm/src/system/memory/tree/public_values.rs
**Metric**: tracegen
**Before**: 18,057.45 ms
**After**: 11,425.45 ms
**Percentage gain**: -36.7%
Workflow: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13145453065
> perf: Compute initial memory Merkle tree using multiple threads

- Cargo.lock
- crates/circuits/primitives/Cargo.toml
building just the circuit primitives crate failed because `serde` needs std enabled.
> chore: update primitive crate to enable serde `std`

- extensions/native/recursion/src/fri/two_adic_pcs.rs
Trivial optimization to save a few allocations.
Reth benchmark comparison: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13212925789
Metric: reth root circuit main cells used
After: (-309252 [-0.9%]) 34,194,443
> perf: trivial opt to reduce alloc in recursion

- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/merkle/mod.rs
- crates/vm/src/system/memory/merkle/trace.rs
- crates/vm/src/system/memory/persistent.rs
Persistent memory boundary chip had a single-threaded bottleneck from poseidon2 hashing. We remove it by parallelizing the hashing, and then update the multiplicities serially afterwards.
Full Perf: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13230601861
Tracegen Perf: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13230648634
Metric:
Reth app proof tracegen time: 
After: (-1227 [-12.5%]) 8,570.09 ms
Towards INT-3256
> perf: parallelize persistent memory finalize

- crates/circuits/primitives/src/README.md
- extensions/ecc/sw-macros/README.md
Hi! While working on the documentation, I noticed some broken links and typos in the `README.md` files. In this PR, I:  
1. **In `crates/circuits/primitives/src/README.md`:**  
- Fixed a typo in the `is_equal_array` module path (changed `moxd.rs` to `mod.rs`). Looks like someone was typing too fast.
2. **In `extensions/ecc/sw-macros/README.md`:**  
- Updated the relative paths to `openvm-algebra-moduli-macros` to point to the correct location (now pointing to `../../algebra/moduli-macros/README.md`).  
These changes are purely cosmetic, but they'll help avoid confusion for anyone new to the project.
> chore: fix broken links and clean up READMEs  

- examples/algebra/Cargo.toml
- examples/i256/Cargo.toml
- examples/keccak/Cargo.toml
- examples/pairing/Cargo.toml
- examples/sha256/Cargo.toml
- examples/u256/Cargo.toml
- Change the OpenVM links in the example guest programs to the `develop` branch so that the lint check passes
> [chore] Fix openvm links for example guest programs

- extensions/ecc/guest/src/ecdsa.rs
- extensions/ecc/tests/programs/examples/ecdsa.rs
- Add constructors for `VerifyingKey<C>` that takes a public key or an affine point
- Add methods to encode and decode in SEC1 format
> [feat] Add constructors for Ecdsa verifying key

- extensions/algebra/moduli-macros/src/lib.rs
- extensions/ecc/guest/src/weierstrass.rs
- changed visibility of `from_const_bytes` in `moduli_declare` to public
- Added a public const constructor for structs created by `impl_sw_affine`
Required by INT-3315
> [chore] Add public `const` constructors

- examples/u256/src/main.rs
I noticed that `openvm::entry!(main);` was placed before the `use` statements. This could lead to compilation issues since the macro might reference types or functions that haven't been declared yet.
P.S. In Rust, `use` statements should always come before their usage. I've moved the macro after the imports to ensure proper compilation.
> chore: fix macro usage order to prevent potential compilation errors

- docs/specs/continuations.md
Hi! This PR fixes a broken link in `continuations.md`, based on the changes from #1048.
The previous link was incorrect, and now it correctly points to `circuit.md`.
> docs: fix broken link continuations.md

- .github/workflows/publish-mdbook.yml
- Converts mdBook publish to a workflow_dispatch instead of `push`
- Run the workflow w/ the desired tag to publish the mdBook to prod
> feat: Convert mdBook publish to workflow dispatch

- book/src/custom-extensions/keccak.md
- book/src/custom-extensions/overview.md
- book/src/custom-extensions/pairing.md
keccak.md
"for using in" → "for use in" (grammatical correction).
overview.m
"a openvm.toml" → "an openvm.toml" (article correction).
pairing.md
"be ran" → "be run" (correct verb tense).
> Grammar Fixes

- extensions/ecc/guest/src/ecdsa.rs
- extensions/ecc/tests/programs/examples/ecdsa.rs
Add constructors for ECDSA verifying key on `main` (mirror commit of https://github.com/openvm-org/openvm/pull/1348).
> [feat] Add constructors for ECDSA verifying key on `main`

- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/metrics/mod.rs
Previously when proving with multiple segments, we execute all segments, but we take the `metrics` from each `segment` before trace generation. When we do trace generation, we finalize memory and then finalize metrics and emit, but at this point the metrics in `segment` are partially empty. This led to the cycle count emission to always be those of the last segment.
The `take` from `metrics` was only needed to get the cycle tracker and function symbol information, so now we do a `partial_take` to avoid cloning.
Old reth benchmark: https://github.com/axiom-crypto/openvm-reth-benchmark/blob/gh-pages/benchmarks-dispatch/refs/heads/main/reth-bb4d597ec9b5edfc486d022fa2ae29202f7e6281-e2fa8f8fba28e8315642c3ddeb11fcd29a7e53d06ecdeba44aae28ee1aef837e.md
New reth benchmark: …
> fix(metrics): cycle count emission across segments

- crates/sdk/src/config/global.rs
previous the Castf config cannot be serde/deserde.
> fix SdkVmConfig serde

- .github/workflows/riscv.yml
- crates/sdk/src/prover/vm/local.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/vm.rs
We modify the `execute_segments` function to `execute_and_then` so that it takes an arbitrary closure that can directly operate on the segment execution result. This way in the `ContinuationProver` implementation of `VmLocalProver` where execution segments are proven serially, we do not need to keep all segment's results (and traces) in memory before starting proving of a single segment.
> feat: memory-efficient `ContinuationProver`

- docs/crates/benchmarks.md
Hi! The link to the Fibonacci example in `benchmarks.md` was pointing to `./programs/fibonacci`, which does not exist in the current directory structure.
> docs: fix broken link in `benchmarks.md`

- extensions/sha256/circuit/src/sha256_chip/air.rs
We have a bug where the message length (in bits) that is appended to the message as part of the SHA-256 padding algorithm is not constrained to be a multiple of 8 (and hence being a length in bytes) but rather to be a multiple of 4 [here](https://github.com/openvm-org/openvm/blob/550feca5cc7bf022c5b41e9d39fe39fa7a2da84f/extensions/sha256/circuit/src/sha256_chip/air.rs#L363C1-L367C1). But we assume that it is a multiple of 8 in another constraint [here](https://github.com/openvm-org/openvm/blob/550feca5cc7bf022c5b41e9d39fe39fa7a2da84f/extensions/sha256/circuit/src/sha256_chip/air.rs#L358C1-L362C1).
The fix is to correctly constrain that the appended length is a multiple of 8. Since the length is stored in little endian, we check that it's first three bits are zero.
> fix: Add constraint to SHA extension that checks if the appended length is a multiple of 8

- extensions/native/circuit/src/jal/tests.rs
I spotted that the result of the function `f` wasn’t being used, even though it seems like the intention was to add it to `test_cases`. I’ve updated the code to push the result properly into the array.
> fix: fix unused result of function call

- extensions/native/circuit/src/poseidon2/air.rs
**Finding Link:** https://cantina.xyz/code/c486d600-bed0-4fc6-aed1-de759fd29fa2/findings/167
While the variable was called `start_top_level`, we only constrained that the top level has `start_top_level = 1` but never that it must be equal to `0` on non-top levels. We change the existing constraint so that it enforces `start_top_level = 1` iff its the start of a top level (meaning previous row is `end` and current row is `incorporate_row`).
Closes INT-3567
> fix: Poseidon2 verify_batch `start_top_level` is not constrained only at start

- extensions/native/compiler/src/asm/compiler.rs
All frame pointers are known at compile time. So we can check stack overflow at compile time.
> [fix] Native ASM compiler checks stack overflow

- extensions/rv32im/circuit/src/README.md
- extensions/rv32im/circuit/src/adapters/alu.rs
- extensions/rv32im/circuit/src/adapters/jalr.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/auipc/core.rs
- extensions/rv32im/circuit/src/base_alu/core.rs
- extensions/rv32im/circuit/src/branch_eq/core.rs
- extensions/rv32im/circuit/src/branch_lt/core.rs
- extensions/rv32im/circuit/src/divrem/core.rs
- extensions/rv32im/circuit/src/jal_lui/core.rs
- extensions/rv32im/circuit/src/jalr/core.rs
- extensions/rv32im/circuit/src/less_than/core.rs
- extensions/rv32im/circuit/src/load_sign_extend/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
- extensions/rv32im/circuit/src/mul/core.rs
- extensions/rv32im/guest/src/io.rs
- Added more detailed code comments for the circuit implementation
- Removed unnecessary constraints
- Added a README describing the statements each circuit must prove. Although it doesn’t prove circuit soundness by itself, it outlines the goal to be met when the circuit is modified.
> [docs] RV32IM Extension specs

- extensions/native/circuit/src/poseidon2/air.rs
- extensions/native/circuit/src/poseidon2/chip.rs
- extensions/native/circuit/src/poseidon2/columns.rs
- extensions/native/circuit/src/poseidon2/tests.rs
- extensions/native/circuit/src/poseidon2/trace.rs
Renames the variable `root_is_on_right` to `sibling_is_on_right` throughout the codebase to better reflect its meaning. The field represents whether the sibling in the Merkle tree is on the right, not the root.
> refactor: Rename `root_is_on_right` to `sibling_is_on_right` for clarity

- extensions/algebra/circuit/src/modular_chip/is_eq.rs
- extensions/algebra/circuit/src/modular_chip/tests.rs
- extensions/algebra/guest/src/lib.rs
This PR fixes a bug in the algebra extension that was found during the internal security review.
**Description:** The setup row of the `ModularIsEqualCoreChip` is unsound. It does not correctly constrain that the modulus is correct. The problem is that the casework on `prefix_sum` that allows constraining `b[i] = N[i]` for the correct indices (when `i > b_diff_idx`) fails on the setup row. The intended behavior on the setup row is that `c_lt_mark = 2` and `lt_marker` has exactly one 2 (at `c_diff_idx`) and the remaining entries are 0s. 
There are three ways in which the setup row is underconstrained:
1. `c_lt_mark` is not constrained to be 2 
2. Even if `c_lt_mark = 2`, `sum_i lt_marker[i]` is not constrained to be 2 (which would ensure that `lt_marker` has exactly one 2 and that the …
> fix: Fix bug in setup row of modular equality chip (`ModularIsEqualCoreChip`)

- extensions/native/compiler/README.md
Rewrite native compiler docs to cover more high-level design and details.
> docs(spec): Native Compiler Docs

- extensions/algebra/circuit/src/fp2.rs
- extensions/algebra/circuit/src/modular_chip/README.md
Added comments.
I didn't add any README documentation since the circuit is easy enough to understand (it uses Mod Builder) and the moduli macros and complex macros already have READMEs.
Note: this PR doesn't have all the comments that I added. This is because I rebased [another PR](https://github.com/openvm-org/openvm/pull/1409) onto this branch and that PR got merged in. So now the diff of this PR doesn't include those comments.
> docs: Algebra VM Extension Specification

- crates/toolchain/build/src/lib.rs
> fix: always filter out build script target

- extensions/native/circuit/src/poseidon2/air.rs
- extensions/native/circuit/src/poseidon2/columns.rs
- extensions/native/circuit/src/poseidon2/trace.rs
Could have also been fixed more simply with `builder.assert_zero(is_exhausted[0])`, but this feels wasteful then we are just adding an all zero column and a bunch of unnecessary constraints.
> fix: prevent starting with is_exhausted in NativePoseidon

- crates/vm/src/arch/segment.rs
If continuation is disabled, VM runtime doesn't segment. This might cause a trace cannot be proven because of its height is too large but this is out of scope of VM runtime.
> fix: Don't segment if continuation is disabled

- crates/cli/src/bin/cargo-openvm.rs
- crates/cli/src/commands/keygen.rs
- crates/cli/src/commands/prove.rs
updates deprecated #[clap(...)] attributes to their modern equivalents in clap 4.x.
> feat: remove deprecated #[clap] attribute

- extensions/native/recursion/src/vars.rs
- extensions/native/recursion/src/view.rs
[Here](https://github.com/openvm-org/openvm/blob/18096f4194b76b743463c0fb39955f24d010e9bf/extensions/native/recursion/src/view.rs#L91) sets `height_max` to `C::F::ORDER_U32 / max_coefficient`. 
Because we check `height < height_max`, `C::F::ORDER_U32 / max_coefficient` is a valid value for `height`.
`C::F::ORDER_U32 / max_coefficient * max_coefficient < C::F::ORDER_U32` because `C::F::ORDER_U32` is a prime and
`max_coefficient > 1`.
closes INT-3636
> fix: recursion max trace height check

- extensions/algebra/guest/src/lib.rs
- extensions/algebra/moduli-macros/src/lib.rs
- extensions/algebra/tests/programs/examples/moduli_setup.rs
- extensions/ecc/guest/src/ecdsa.rs
- extensions/ecc/sw-macros/src/lib.rs
- extensions/ecc/tests/programs/examples/decompress_invalid_hint.rs
- extensions/ecc/tests/programs/examples/ecdsa.rs
Finding by @lispc 
- (style) rename previous `IntMod::assert_unique` to `IntMod::assert_reduced` and move the implementation using `iseqmod` into macro since it's specific to the use of special intrinsic.
- Add new `is_reduced() -> bool` that checks if an integer representation is less than the modulus. Does simple byte-wise comparison check.
- Update ECDSA verify and recover functions so it returns Error when `r` or `s` are not in `[1,n]`.
Closes INT-3517
> fix: ECDSA verify should not panic when signature not reduced

- crates/circuits/primitives/src/range/tests/list/columns.rs
- crates/circuits/primitives/src/range_gate/mod.rs
- crates/circuits/primitives/src/range_tuple/mod.rs
- crates/vm/src/system/phantom/mod.rs
I have ensured that all `*Cols` structs that are stack allocatable, in other words all structs in the codebase that derive `AlignedBorrow`, have `repr(C)` for stable memory layout.
Closes INT-3477
> fix: ensure all `AlignedBorrow` cols use `repr(C)`

- crates/circuits/mod-builder/src/builder.rs
- extensions/ecc/circuit/src/weierstrass_extension.rs
- extensions/ecc/sw-macros/src/lib.rs
- extensions/ecc/tests/programs/Cargo.toml
- extensions/ecc/tests/programs/examples/decompress.rs
- extensions/ecc/tests/programs/examples/decompress_invalid_hint.rs
- extensions/ecc/tests/src/lib.rs
- Fix `find_non_qr` for cases when p = 1 mod 4 but is not 5 mod 8.
- Fix the `num_limbs` of `prime_limbs` in `FieldExpr` (this issue arose when adding tests with 224-bit moduli; it doesn't affect the soundness of the Mod builder but will cause the correct trace to fail).
Resolves INT-3640
> fix: `find_non_qr` doesn't work for `p = 1 mod 4`

- extensions/native/recursion/src/commit.rs
- extensions/native/recursion/src/fri/mod.rs
- extensions/native/recursion/src/fri/two_adic_pcs.rs
- extensions/native/recursion/src/stark/mod.rs
The length of `proof.commit_phase_commits` is not validated and [here](https://github.com/openvm-org/openvm/blob/18096f4194b76b743463c0fb39955f24d010e9bf/extensions/native/recursion/src/fri/two_adic_pcs.rs#L125) we directly use it as the maximum log trace height.
close INT-3646
> fix: Validate length of proof.commit_phase_commits

- extensions/keccak256/circuit/src/air.rs
- extensions/keccak256/circuit/src/columns.rs
> fix: constrain `pc` to be same for intermediate keccak rows

- crates/circuits/mod-builder/src/builder.rs
- crates/circuits/mod-builder/src/field_variable.rs
- crates/circuits/mod-builder/src/symbolic_expr.rs
- crates/circuits/mod-builder/src/tests.rs
- extensions/algebra/circuit/src/fp2.rs
- extensions/algebra/tests/programs/examples/moduli_setup.rs
Previously the trace generation for ModBuilder was not calculating the number of limbs necessary in a way consistent with the constraints. This was because there were some underestimates when the prime is much smaller than $`2^\textrm{num\_limbs * limb\_bits}`$. We fix it by updating all calculations to use the theoretical bound that an input or saved var have big integer value in $`[0, 2^\text{num\_limbs * limb\_bits})`$ rather than $[0, p)$.
This causes no soundness bugs, but it does affect completeness of tracegen.
closes INT-3641
> fix: completeness of ModBuilder trace generation

- extensions/pairing/guest/src/bls12_381/pairing.rs
- extensions/pairing/guest/src/bls12_381/tests.rs
- extensions/pairing/guest/src/bn254/mod.rs
- extensions/pairing/guest/src/bn254/pairing.rs
- extensions/pairing/guest/src/bn254/tests.rs
As part of the pairing internal security review, I found some unvalidated constants so I'm adding tests for them here.
> chore: Add tests for some constants in the pairing extension

- extensions/pairing/tests/src/lib.rs
The pairing hint fallback tests take forever to run (14 mins compared to 1-3 mins for other extensions), and they are triggered in the CI workflow.
This PR adds `#[ignore]` to these tests.
> chore: Add `#[ignore]` to pairing fallback tests

- docs/specs/ISA.md
- docs/specs/RISCV.md
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/load_sign_extend/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
- extensions/sha256/guest/src/lib.rs
RISC-V spec says that 
>  Loads and stores whose effective address is not naturally aligned to the referenced datatype (i.e., the effective address is not divisible by the size of the access in bytes) have behavior dependent on the EEI.
Our circuits already support arbitrary misaligned accesses, so this PR just updated execution (in the LoadStore Adapter `preprocess`) so trace generation actually handles misaligned accesses properly.
Reminder on how it works: 
If you want to access `ptr_val`, then the circuit will do block access of size 4 on `[ptr_val - shift_amt..ptr_val - shift_amt + 4]` where `shift_amt` can be `0,1,2,3` for byte accesses, `0,2` for half word, and `0` only for word. The block access will always work regardless of alignment because the memory access adapter will handle …
> docs: update specs on misaligned RV32 access not allowed

- crates/toolchain/openvm/src/io/mod.rs
This resolves INT-3660.
The comment is outdated since we deserialize stuff from the input stream differently in ZKVM.
> chore: rewrite an outdated comment

- Cargo.lock
- crates/sdk/Cargo.toml
- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/halo2.rs
- crates/sdk/src/prover/mod.rs
- crates/sdk/src/types.rs
- extensions/native/recursion/src/halo2/mod.rs
- extensions/native/recursion/src/halo2/wrapper.rs
- Rename the existing `EvmProof` into `RawEvmProof`
- Add a more semantic type `EvmProof` into `openvm-sdk`. 
- [Breaking change] Replace all `RawEvmProof` usages in the SDK interface with `EvmProof`
- Serialize `EvmProof` in json instead of `bitcode`. All fields are represented as bytes.
closes INT-3596
> refactor: Add type `EvmProof` into openvm-sdk

- crates/toolchain/platform/src/heap/embedded.rs
This resolves INT-3659.
The problem was that we could potentially try to initialize about `usize::MAX` of heap memory due to unchecked subtraction.
> fix: check the heap size on memory initialization

- crates/circuits/mod-builder/src/README.md
I rewrote the Mod Builder spec to better explain its high-level design without confusing the reader with too many code-level references.
Closes INT-3657
> spec: Rewrite Mod Builder spec

- benchmarks/programs/kitchen-sink/src/main.rs
- crates/toolchain/openvm/src/io/read.rs
- extensions/algebra/moduli-macros/src/lib.rs
- extensions/bigint/guest/src/i256.rs
- extensions/bigint/guest/src/u256.rs
- extensions/pairing/tests/programs/examples/fp12_mul.rs
- extensions/pairing/tests/programs/examples/pairing_check.rs
- extensions/pairing/tests/programs/examples/pairing_check_fallback.rs
- extensions/pairing/tests/programs/examples/pairing_line.rs
- extensions/pairing/tests/programs/examples/pairing_miller_loop.rs
- extensions/pairing/tests/programs/examples/pairing_miller_step.rs
Rust treats `[u8; LEN]` as having alignment of `1`, so if you unsafely transmute or convert a slice to `[T; LEN]` which expects alignment of `align_of<T>()`, then this may result in misaligned load/store instructions, often during operations like memcpy. OpenVM RV32 does not support misaligned access (see https://github.com/openvm-org/openvm/pull/1474), so we make sure all our use of unsafe Rust has proper alignment.
> fix: alignment in unsafe rust

- crates/toolchain/openvm/src/io/mod.rs
- docs/specs/ISA.md
- docs/specs/RISCV.md
- extensions/rv32im/circuit/src/hintstore/README.md
Updates specs on the RISC-V execution environment for user IO.
Update internal docs to explain soundness of hint buffer. This relies on an invariant of the memory bus which is stated in https://github.com/openvm-org/openvm/pull/1490.
Also found that our `read_vec_with_len` implementation uses a bit of unsafe Rust that does not quite match the documented safety assumptions (though in practice currently does not have any problems). This is around a hidden assumption that the allocator always allocates on a 4-byte boundary.
> docs: update specs on RISC-V execution environment

- crates/circuits/primitives/src/utils.rs
- crates/circuits/primitives/src/var_range/mod.rs
- crates/circuits/sha256-air/src/utils.rs
- crates/vm/src/system/memory/volatile/mod.rs
- docs/specs/memory.md
VolatileBoundaryAir was using IsLessThanArray, which compares `x < y` **assuming** that `x, y` are both in a range `[0, max_bits)`. But for the volatile boundary case, we **must** range check this assumption, where `x = (addr_space, pointer)`.
We fix this by decomposing `addr_space, pointer` both into limbs and range checking.
I slightly optimized to only support `addr_space in [0, 2^range_max_bits)` and `pointer in [0, 2^{2*range_max_bits})` but did it with configurable constants so this could be changed to support a greater max bits in address space in the future.
Comparison Benchmark: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13963291660 (no significant perf diff)
Closes INT-3664
> fix: `VolatileBoundaryAir` range checks addresses

- crates/vm/src/arch/config.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/utils/stark_utils.rs
- crates/vm/tests/integration_test.rs
- docs/specs/memory.md
We were using `as_height` but it is actually `log2(1 + 2^as_height)`.
> fix: `addr_space_max_bits` in `VolatileBoundaryChip` constructor

- crates/circuits/primitives/src/bitwise_op_lookup/mod.rs
- crates/circuits/primitives/src/range_tuple/mod.rs
- crates/circuits/primitives/src/var_range/mod.rs
- crates/vm/src/arch/extensions.rs
- crates/vm/src/system/memory/adapter/mod.rs
- crates/vm/src/system/memory/controller/mod.rs
- extensions/native/circuit/src/fri/mod.rs
- extensions/native/circuit/src/jal/mod.rs
- extensions/native/circuit/src/poseidon2/chip.rs
- extensions/rv32im/circuit/src/hintstore/mod.rs
These are public chip fields that were previously used to implement `Stateful`. Exposing them publicly allows an external repo to handle serialization and deserialization of those fields. The list of these fields is tracked here: https://docs.google.com/document/d/1yFUDUlXcObTYrLBWoDV0I-zmBQJ1kIQ9LAv-_fCPb8U
> chore: `pub` chip fields necessary for serialization/deserialization

- Cargo.lock
- Cargo.toml
- extensions/native/recursion/src/stark/mod.rs
In recursion program, add a check that the number of after challenge commitments equals the number of phases as recorded in the vkey. This is just for clarity and not a soundness fix: the control flow is already determined by `num_phases` from the vkey, and even if an out of bounds memory access were made, it is equivalent to if an array of the correct length 1 were provided, but where the value was incorrect -- this would still be caught by the verification algorithm.
Add some more comments in recursion program.
Updates stark-backend commit to sync with https://github.com/openvm-org/stark-backend/pull/57
> feat(recursion): add clarifying OOB check

- Cargo.lock
- book/src/getting-started/quickstart.md
- book/src/writing-apps/overview.md
- crates/cli/Cargo.toml
- crates/cli/src/commands/prove.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/input.rs
- crates/cli/src/lib.rs
- crates/cli/src/util.rs
breaking changes:
CLI input is now either 
1. one single hex string
1. a JSON file containing an array of hex strings.
Each hex string (either in the file or the direct input) is either:
1. Hex strings of bytes, which is prefixed with 0x01
1. Hex strings of native field elements (represented as u32, little endian), prefixed with 0x02
> chore: change cli input format

- audits/v1-internal/extension-algebra.md
- audits/v1-internal/extension-bigint.md
- audits/v1-internal/extension-native.md
- audits/v1-internal/isa.md
- audits/v1-internal/native-compiler.md
- audits/v1-internal/recursion-program.md
- audits/v1-internal/riscv-transpiler.md
- audits/v1-internal/rust-toolchain.md
- audits/v1-internal/stark-backend.md
```bash
codespell --skip="Cargo.lock,./book/pnpm-lock.yaml,*.txt,./crates/toolchain/openvm/src/memcpy.s,./crates/toolchain/openvm/src/memset.s,target" --ignore-words=.codespellignore -w
```
> chore: fix audit typos

- Cargo.lock
- crates/cli/src/default.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/codec.rs
- crates/sdk/src/lib.rs
- crates/sdk/tests/integration_test.rs
This doesn't yet change any SDK output methods, but adds a codec to encode/decode the inner STARK proof, specialized to BabyBearPoseidon2Config and FRI.
Closes INT-3598
> feat(sdk): hardware and language independent encoding of inner STARK `Proof`

- crates/vm/src/system/memory/offline.rs
This removes the `memory_image_to_paged_vec` function that did nothing and took time to do so (it used to convert from `FxHashMap` to `PagedVec`)
> chore: remove redundant `memory_image_to_paged_vec`

- crates/circuits/primitives/src/bitwise_op_lookup/mod.rs
- crates/circuits/primitives/src/range_tuple/mod.rs
- crates/circuits/primitives/src/var_range/mod.rs
Implement `AsRef` trait for `SharedBitwiseOperationLookupChip` and `SharedRangeTupleCheckerChip` so that the inner chip is accessible for serialization/deserialization
> chore: impl `AsRef` for `SharedBitwiseOperationLookupChip` and `SharedRangeTupleCheckerChip`

- crates/sdk/src/codec.rs
- crates/sdk/src/fs.rs
- crates/sdk/tests/integration_test.rs
- Implement `Encode`/`Decode` for `Proof<SC>`/`RootVmVerifierInput<SC>`/`ContinuationVmProof<SC>`
- [Breaking change] Use `Encode`/`Decode` for `ContinuationVmProof<SC>` FS functions
- Add FS functions for `RootVmVerifierInput<SC>`
close INT-3580
> feat: Cross-language Serialization for RootVmVerifierInput/ContinuationVmProof

- benchmarks/src/bin/fib_e2e.rs
- benchmarks/src/bin/kitchen_sink.rs
- benchmarks/src/bin/pairing.rs
- benchmarks/src/bin/verify_fibair.rs
- benchmarks/src/utils.rs
- crates/cli/src/commands/build.rs
- crates/cli/src/commands/keygen.rs
- crates/cli/src/commands/prove.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/verify.rs
- crates/sdk/examples/sdk_app.rs
- crates/sdk/examples/sdk_evm.rs
- crates/sdk/src/lib.rs
- crates/sdk/tests/integration_test.rs
This change introduces a generic type for Sdk (with a typedef for `Sdk` that uses `BabyBearPoseidon2Engine`). This is to allow Sdk usage with different engines that still use the same `StarkGenericConfig = BabyBearPoseidon2Config`.
This will require changes in other repos, but it is inevitable since `let sdk = Sdk;` is now an invalid assignment.
> feat: `GenericSdk<E: StarkFriEngine<BabyBearPoseidon2Config>>`

- extensions/native/circuit/src/fri/mod.rs
Public `get_height()` method used to deserialize `FriReducedOpeningChip`
> chore: public `get_height()` of `FriReducedOpeningChip`

- crates/circuits/mod-builder/src/builder.rs
- extensions/algebra/tests/programs/examples/invalid-setup.rs
- extensions/algebra/tests/src/lib.rs
- extensions/ecc/tests/programs/Cargo.toml
- extensions/ecc/tests/programs/examples/invalid_setup.rs
- extensions/ecc/tests/src/lib.rs
Added debug assertions in execute to check the values in the setup row are correct.
Added `#[should_panic]` tests:
- for ecc that fail since the order of curves in `sw_init!` does not match the config
- for algebra that fail since the order of moduli in `moduli_init!` does not match the config.
Closes INT-3698
> chore: Add debug assertions for the setup row of Mod Builder chips

- .github/workflows/lints.yml
- extensions/ecc/tests/programs/examples/ec_nonzero_a.rs
The linter did not lint some guest programs in the ecc tests because the `p256` feature was not enabled.
> fix: Add p256 feature to clippy when linting ecc test guest programs

- book/src/custom-extensions/algebra.md
- book/src/custom-extensions/ecc.md
Added a note to the algebra and ecc extension pages that mentions that the order of items in the `moduli_init`, `complex_init` and `sw_init` macros must match the order in the vm config toml file.
Closes INT-3696
> chore: Update book to specify order of items in init! macros

- .github/workflows/docs.yml
The two step build requires the same cargo version for graphics to line up.
> fix(ci): rust docs build workflow requires nightly

- Cargo.lock
- Cargo.toml
- audits/v1-internal/stark-backend.md
Update stark-backend for https://github.com/openvm-org/stark-backend/pull/62 
Update plonky3 commit to include the patch https://github.com/Plonky3/Plonky3/pull/759 fixing the Rust FRI verifier. 
Description of the security issue: https://github.com/Plonky3/Plonky3/security/advisories/GHSA-m23j-cj9m-ppg9
> fix: plonky3 FRI verifier

- crates/vm/src/arch/execution.rs
Enable `PhantomChip` to implement `Send` so that it can be serialized and deserialized in parallel
> chore: Implement `Send` for `PhantomChip`

- .github/workflows/cli.yml
- crates/toolchain/build/src/lib.rs
`cargo openvm build` will use `rustup` to check if the required nightly toolchain and `rust-src` component are installed, and will install them if they are not. If this step fails, then the entire build process errors (I wasn't sure if this was the preferred behavior or if we should let the rest of the cargo build attempt continue, but it felt like for earlier stopping and debugging it's better to fail the process).
Updated only the cli workflow because in multithreaded tests, I don't want it to try to install the toolchain in multiple threads simultaneously.
closes INT-2911
> feat(cli): install pinned nightly toolchain automatically

- crates/circuits/primitives/src/bitwise_op_lookup/mod.rs
- crates/circuits/primitives/src/range_tuple/mod.rs
- crates/circuits/primitives/src/var_range/mod.rs
- crates/vm/src/arch/extensions.rs
This fix only affects logging and segmentation logic during execution under certain misconfigured parameter settings. It does not affect any circuit soundness.
Fixes two separate issues around segmentation with respect to fixed-size traces: the first being that `constant_trace_height` was not implemented for some wrapper types, and the second being that
`VmChipComplex::current_trace_cells` did not check if a chip had constant trace height.
> fix: don't segment due to fixed-size traces

- .github/workflows/primitives.yml
- crates/circuits/mod-builder/src/tests.rs
The symbolic expression multiplication unit test was being run with an incorrect expected result. The test became out-of-date after #1473 changed the `max_abs` method.
This PR updates the test with the correct expected result and adds the Mod Builder crate's unit tests to the CI workflow.
This change has no impact on the functionality of the Mod Builder crate as it only updates the tests.
> fix: Update Mod Builder symbolic expression multiplication test

- .gitignore
- Cargo.lock
- benchmarks/Cargo.toml
- benchmarks/src/bin/ecrecover.rs
- crates/toolchain/tests/Cargo.toml
- crates/toolchain/tests/tests/transpiler_tests.rs
- crates/vm/derive/src/lib.rs
- extensions/algebra/circuit/src/config.rs
- extensions/bigint/circuit/src/extension.rs
- extensions/ecc/circuit/src/config.rs
- extensions/keccak256/circuit/src/extension.rs
- extensions/native/circuit/src/extension.rs
- extensions/pairing/circuit/src/config.rs
- extensions/rv32im/circuit/src/extension.rs
- extensions/sha256/circuit/src/extension.rs
- use absolute paths for structs used only in the derive macro
> fix: use absolute paths in `VmConfig` derive macro

- crates/sdk/src/keygen/dummy.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/prover/root.rs
- crates/vm/src/arch/vm.rs
- crates/vm/tests/integration_test.rs
- Not a soundness issue. Just an issue of `RootVerifierLocalProver` implementation in SDK.
- In some edge cases, the trace heights of the root verifier circuit are less than the required heights. In this case, `RootVerifierLocalProver` should pad its traces to the required heights.
- [Breaking change] Add a new field `internal_heights` into `RootVerifierProvingKey`.
> fix: RootVerifierLocalProver should respect AIR heights

- .github/workflows/sdk.yml
- .gitmodules
- Cargo.lock
- Cargo.toml
- crates/cli/src/commands/build.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/verify.rs
- crates/cli/src/default.rs
- crates/cli/tests/app_e2e.rs
- crates/sdk/Cargo.toml
- crates/sdk/contracts/.gitignore
- crates/sdk/contracts/abi/IOpenVmHalo2Verifier.json
- crates/sdk/contracts/foundry.toml
- crates/sdk/contracts/src/IOpenVmHalo2Verifier.sol
- crates/sdk/contracts/template/OpenVmHalo2Verifier.sol
- crates/sdk/contracts/test/OpenVmHalo2Verifier.t.sol
- crates/sdk/contracts/test/helpers/LibString.sol
- crates/sdk/contracts/test/helpers/MockDeps.sol
- crates/sdk/examples/sdk_evm.rs
- crates/sdk/guest/src/main.rs
- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/types.rs
- crates/sdk/tests/integration_test.rs
- extensions/native/recursion/src/halo2/wrapper.rs
This PR adds a new verifier contract generation that wraps the original `snark-verifier` output (via inheritance). The goal of this wrapper `OpenVmHalo2Verifier` is to expose a more friendly interface to users that cleanly separates out the guest program public values. `OpenVmHalo2Verifier` exposes the following interface:
```solidity
interface IOpenVmHalo2Verifier {
function verify(bytes calldata publicValues, bytes calldata proofData, bytes32 appExeCommit, bytes32 appVmCommit)
external
view;
}
```
- `publicValues`: The bytes revealed in the OpenVM guest program packed together.
- `proofData`: Defined as `abi.encodePacked(KZG accumulators, publicValuesSuffix)`
- `appExeCommit`: The commitment to the OpenVM application executable whose execution is being verified.
- `appVmCommit`: The …
> feat: `OpenVmHalo2Verifier`

- Cargo.lock
- benchmarks/prove/src/bin/fib_e2e.rs
- benchmarks/prove/src/bin/kitchen_sink.rs
- benchmarks/prove/src/util.rs
- crates/cli/src/commands/prove.rs
- crates/sdk/src/config/mod.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/mod.rs
- crates/sdk/src/prover/stark.rs
Introduce `AggregationTreeConfig` struct for simple configuration of aggregation tree.
These were already in the provers, but not exposed to be changeable. 
Breaking API changes in SDK:
- `AggStarkProver::new`
- `ContinuationProver::new`
- `Sdk` now internally contains `AggregationTreeConfig`, although `Sdk::new()` is unchanged and just sets a default
Towards INT-3302
> feat(sdk)!: configurable aggregation tree shape in SDK

- crates/sdk/src/config/mod.rs
The total proving time of `num_children_internal=4` vs 3 is about the same, but 4 leads to the `internal.0` verifier circuit's size being larger than the leaf verifier, so for the sake of having smaller circuits, we switch to `3` as the default.
This is configurable via CLI and SDK, so it's just a default for convenience.
> perf: set default `num_children_internal=3`

- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/paged_vec.rs
- crates/vm/src/system/memory/tree/public_values.rs
Not merging to main
Add `GuestMemory` trait and implement for `AddressMap`. We are moving more towards a trait based style to re-use code when different types of memory might be swapped out.
> feat: `GuestMemory` trait

- crates/vm/src/arch/vm.rs
The circuit flamegraphs being generated were incorrect due to a bug in the multi-segment execution logic. In particular, each segment takes the metric data from the previous segment, but the first segment was using an empty metrics struct instead of being initialized with the correct `fn_bounds` data.
> fix: circuit flamegraphs with segmentation

- .github/workflows/lints.yml
- benchmarks/execute/Cargo.toml
- benchmarks/prove/Cargo.toml
- benchmarks/prove/src/bin/fib_e2e.rs
- benchmarks/prove/src/bin/kitchen_sink.rs
- crates/cli/Cargo.toml
- crates/cli/src/bin/cargo-openvm.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/prove.rs
- crates/cli/src/commands/verify.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/mod.rs
- crates/sdk/src/types.rs
- crates/sdk/tests/integration_test.rs
- crates/vm/Cargo.toml
- extensions/bigint/circuit/Cargo.toml
- extensions/keccak256/circuit/Cargo.toml
- extensions/native/recursion/Cargo.toml
- extensions/native/recursion/src/halo2/mod.rs
- extensions/native/recursion/src/halo2/wrapper.rs
- extensions/rv32im/circuit/Cargo.toml
- extensions/sha256/circuit/Cargo.toml
Previously we were very sloppy with enabling of features: `openvm-native-recursion` was always enabling the `snark-verifier` feature "revm" which imports a fixed version of revm only used for testing purposes. Since revm version changes rather frequently, this can cause Cargo dependency conflicts if someone wants to use the SDK with another version of revm.
I've added new features "evm-prove" and "evm-verify" to `openvm-native-recursion`, `openvm-sdk`, `cargo-openvm` so that 
- "evm-prove" allows for generation of EVM halo2 proofs, which just enables some additional features in `snark-verifier` but no additional other dependencies.
- "evm-verify" allows for revm simulation of EVM contract calls to verify halo2 proofs. This includes imports of `revm` and some `alloy` crates, with fixed …
> chore: feature gate `revm` and `alloy` imports

- crates/vm/src/arch/vm.rs
The circuit flamegraphs being generated were incorrect due to a bug in the multi-segment execution logic. In particular, each segment takes the metric data from the previous segment, but the first segment was using an empty metrics struct instead of being initialized with the correct `fn_bounds` data.
> fix: circuit flamegraphs with segmentation (#1571)

- book/src/writing-apps/verify.md
Update docs for the new EVM proof format.
Closes INT-3576
> docs: Update book with new evm proof format

- Cargo.lock
- Cargo.toml
- book/src/writing-apps/verify.md
- crates/cli/src/commands/verify.rs
- crates/sdk/Cargo.toml
- crates/sdk/contracts/template/OpenVmHalo2Verifier.sol
- crates/sdk/contracts/test/OpenVmHalo2Verifier.t.sol
- crates/sdk/examples/sdk_evm.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/types.rs
- crates/sdk/tests/integration_test.rs
- docs/specs/continuations.md
- extensions/native/recursion/src/fri/two_adic_pcs.rs
This PR alters the JSON proof outputted by `cargo openvm prove` to conform to the format of the verifier contract.
> chore: alter json format of proof to align with verifier contract

- crates/vm/src/arch/config.rs
- crates/vm/src/arch/execution.rs
- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/integration_api.rs
- crates/vm/src/arch/testing/memory/air.rs
- crates/vm/src/arch/testing/memory/mod.rs
- crates/vm/src/arch/testing/mod.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/offline.rs
- crates/vm/src/system/memory/offline_checker/columns.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/paged_vec.rs
- crates/vm/src/system/mod.rs
- crates/vm/src/system/native_adapter/mod.rs
- extensions/rv32im/circuit/src/adapters/mod.rs
- extensions/rv32im/circuit/src/adapters/rdwrite.rs
- extensions/rv32im/circuit/src/auipc/core.rs
- extensions/rv32im/circuit/src/auipc/mod.rs
- extensions/rv32im/circuit/src/auipc/tests.rs
- extensions/rv32im/circuit/src/base_alu/tests.rs
- extensions/rv32im/circuit/src/extension.rs
- extensions/rv32im/circuit/src/hintstore/mod.rs
- extensions/rv32im/circuit/src/hintstore/tests.rs
- extensions/rv32im/circuit/src/jal_lui/core.rs
- extensions/rv32im/circuit/src/jal_lui/mod.rs
- extensions/rv32im/circuit/src/jal_lui/tests.rs
- extensions/rv32im/circuit/src/jalr/tests.rs
- extensions/rv32im/circuit/src/load_sign_extend/tests.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
- extensions/rv32im/circuit/src/shift/tests.rs
- deleting `Vm{Adapter,Core}Chip` traits
- no more records, directly use trace buffer
- jal_lui chip is a demonstration of the new changes with working unit tests
- changed unit tester
> feat(new-execution): `TracingMemory` and removal of records/logs

- crates/circuits/mod-builder/src/core_chip.rs
- crates/vm/src/arch/execution.rs
- crates/vm/src/arch/integration_api.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/system/public_values/core.rs
- extensions/algebra/circuit/src/modular_chip/is_eq.rs
- extensions/algebra/circuit/src/modular_chip/tests.rs
- extensions/native/circuit/src/castf/core.rs
- extensions/native/circuit/src/field_arithmetic/core.rs
- extensions/native/circuit/src/field_extension/core.rs
- extensions/native/circuit/src/loadstore/core.rs
- extensions/rv32im/circuit/src/auipc/core.rs
- extensions/rv32im/circuit/src/base_alu/core.rs
- extensions/rv32im/circuit/src/branch_eq/core.rs
- extensions/rv32im/circuit/src/branch_lt/core.rs
- extensions/rv32im/circuit/src/divrem/core.rs
- extensions/rv32im/circuit/src/jal_lui/core.rs
- extensions/rv32im/circuit/src/jalr/core.rs
- extensions/rv32im/circuit/src/less_than/core.rs
- extensions/rv32im/circuit/src/load_sign_extend/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
- extensions/rv32im/circuit/src/mul/core.rs
- extensions/rv32im/circuit/src/mulh/core.rs
- extensions/rv32im/circuit/src/shift/core.rs
- introduce a new generic `InsExecutorE1` trait 
- add `InsExecutor::execute_e1` for rv32im instructions
> feat(new-execution): add execute functions for rv32im instructions

- .github/workflows/riscv.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
> ci: bump actions/checkout to v4

- crates/cli/src/commands/build.rs
necessary as temporary workaround for supporting custom getrandom_backend: https://docs.rs/getrandom/latest/getrandom/#custom-backend
> feat(cli): allow `RUSTFLAGS` in build command

- crates/cli/src/commands/prove.rs
- crates/continuations/src/verifier/internal/types.rs
- crates/sdk/src/codec.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/stark.rs
- crates/sdk/src/types.rs
- Add new type `E2eStarkProof` as the format of the final internal proof. `E2eStarkProof` supports `Encode` so it can be deserialized in other languages.
- Add function `wrap_e2e_stark_proof` to wrap the final internal proof to `RootVerifierInput`.
- Add `cargo openvm prove stark` to generate e2e stark proof.
closes INT-3784
> feat: Add e2e stark proof support

- Cargo.lock
- crates/toolchain/openvm/src/io/mod.rs
- crates/vm/src/arch/vm.rs
- docs/specs/ISA.md
- docs/specs/isa-table.md
- extensions/native/circuit/src/loadstore/core.rs
- extensions/rv32im/circuit/src/extension.rs
- extensions/rv32im/circuit/src/hintstore/mod.rs
- extensions/rv32im/guest/Cargo.toml
- extensions/rv32im/guest/src/io.rs
- extensions/rv32im/guest/src/lib.rs
- extensions/rv32im/tests/Cargo.toml
- extensions/rv32im/tests/programs/examples/hint_load_by_key.rs
- extensions/rv32im/tests/src/lib.rs
- extensions/rv32im/transpiler/src/instructions.rs
- extensions/rv32im/transpiler/src/lib.rs
- Add `kv_store` into `Streams`. More details at `docs/specs/ISA.md`.
- Add a new phantom instruction `Rv32HintLoadByKey` which can hint data based on a key at runtime. More details at `docs/specs/ISA.md`.
- SDK support will be added in the future PRs.
close INT-3893
> feat: Add Rv32HintLoadByKey

- crates/vm/src/system/memory/online.rs
one line fix. now that we're only initializing `TracingMemory` with `new`, we should remove this line from `with_image`
> fix(new-execution): don't override min block size

- Cargo.lock
- crates/cli/src/commands/setup.rs
- crates/cli/src/default.rs
- crates/continuations/src/verifier/internal/mod.rs
- crates/continuations/src/verifier/internal/vars.rs
- crates/continuations/src/verifier/root/mod.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/keygen/asm.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/stark.rs
- crates/sdk/tests/integration_test.rs
- extensions/native/compiler/src/asm/compiler.rs
- Add a function `build_kernel_asm` into `RootVmVerifierConfig`. The generated ASM can be used in kernel functions for guest program to verify starks. More details could be found in the doc comments of the function.
- Fix a confusing naming. `num_public_values` is actually the number of user public values instead of the number of public values of the proof. Use `num_user_public_values` instead.
closes INT-3894
> feat: Root Verifier ASM

- crates/vm/src/arch/testing/mod.rs
- extensions/rv32im/circuit/src/base_alu/tests.rs
- extensions/rv32im/circuit/src/divrem/tests.rs
- extensions/rv32im/circuit/src/hintstore/tests.rs
- extensions/rv32im/circuit/src/load_sign_extend/tests.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
Fixed an error in divrem negative tests. The trace pranking was done incorrectly. 2 instructions were being called (so the trace had height 2) each time but only one of the rows was being modified. Changed it so only one instruction is called each time
Also, made the setup_tracing the default
> fix: divrem tests

- Cargo.lock
- Cargo.toml
- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
Truncates the patch version from halo2 verifier.
Also bumps the openvm version to 1.1.2
> feat: truncate patch on verifier version

- book/src/SUMMARY.md
- book/src/writing-apps/solidity.md
Adds instructions on using the solidity sdk to the book.
Closes INT-3974
> docs: solidity sdk

- Cargo.lock
- benchmarks/prove/src/bin/fib_e2e.rs
- benchmarks/prove/src/bin/verify_fibair.rs
- crates/sdk/src/commit.rs
- crates/sdk/src/config/mod.rs
- crates/sdk/src/keygen/dummy.rs
- crates/sdk/tests/integration_test.rs
- crates/toolchain/instructions/Cargo.toml
- crates/toolchain/instructions/benches/program_serde.rs
- crates/toolchain/instructions/src/program.rs
- crates/toolchain/transpiler/src/elf.rs
- crates/toolchain/transpiler/src/lib.rs
- crates/vm/src/arch/config.rs
- crates/vm/src/system/program/tests/mod.rs
- extensions/native/compiler/src/conversion/mod.rs
- Remove `max_num_public_values` in `Program`/`Elf`.
- Improve serialization/deserialization of `Program`.
For a Program with 100,000 instructions:
Previous:
- Serialize: 3.1969ms
- Deserialize: 3.2417ms
- Size: 3625020 bytes
Now:
- Serialize: 1.3015ms
- Deserialize: 1.9343ms
- Size: 4000024 bytes
closes INT-3131
closes INT-3771
> refactor: ELF and Program

- Cargo.lock
- crates/vm/src/arch/integration_api.rs
- crates/vm/src/arch/testing/mod.rs
- extensions/bigint/circuit/Cargo.toml
- extensions/bigint/circuit/src/extension.rs
- extensions/bigint/circuit/src/lib.rs
- extensions/bigint/circuit/src/tests.rs
- extensions/rv32-adapters/src/heap.rs
- extensions/rv32-adapters/src/heap_branch.rs
- extensions/rv32-adapters/src/lib.rs
- extensions/rv32-adapters/src/vec_heap.rs
- extensions/rv32im/circuit/Cargo.toml
- extensions/rv32im/circuit/src/adapters/alu.rs
- extensions/rv32im/circuit/src/adapters/branch.rs
- extensions/rv32im/circuit/src/adapters/mod.rs
- extensions/rv32im/circuit/src/adapters/mul.rs
- extensions/rv32im/circuit/src/base_alu/core.rs
- extensions/rv32im/circuit/src/base_alu/tests.rs
- extensions/rv32im/circuit/src/branch_eq/core.rs
- extensions/rv32im/circuit/src/branch_lt/core.rs
- extensions/rv32im/circuit/src/divrem/core.rs
- extensions/rv32im/circuit/src/extension.rs
- extensions/rv32im/circuit/src/less_than/core.rs
- extensions/rv32im/circuit/src/less_than/tests.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
- extensions/rv32im/circuit/src/mul/core.rs
- extensions/rv32im/circuit/src/mulh/core.rs
- extensions/rv32im/circuit/src/shift/core.rs
- extensions/rv32im/circuit/src/shift/tests.rs
Implemented e1 and e3 for HeapBranch, Heap, and VecHeap adapters. Updated the Bigint circuit correspondingly. Had to make some changes in the interfaces of rv32im Steps. In particular
- Changed Reads type `([u8; N], [u8; N])` into `Into<[[u8;N];2]>` and Writes type `[u8; N]` into `From<[[u8;N];1]>`. This change corresponds to what we used to do with the previous integration API in order to make the interfaces to match.
- Got rid of TraceAdapterContext in a lot of places. This is because the same Step can be using different AdapterSteps that require different TraceContexts. Or even the AdapterStep might require a `TraceContext` that the Step doesn't have. The easy solution was to implement AdapterSteps in a similar way as in the previous integration API. That is, added the necessary fields …
> feat: bigint circuit to compile

- Cargo.lock
- crates/vm/src/arch/execution_control.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/testing/memory/mod.rs
- crates/vm/src/arch/testing/mod.rs
- crates/vm/src/system/memory/adapter/mod.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/merkle/mod.rs
- crates/vm/src/system/memory/merkle/tests/mod.rs
- crates/vm/src/system/memory/merkle/trace.rs
- crates/vm/src/system/memory/merkle/tree.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/persistent.rs
- extensions/rv32im/circuit/src/branch_lt/tests.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
- extensions/rv32im/circuit/src/mulh/tests.rs
Resolves INT-3801.
- Added memory access adapters. To improve:
* Allocate the trace buffer once before filling it as opposed to pushing to `Vec` how it's done now,
* Maybe not call `get_f` too often (although I don't know how to avoid it normally).
- Added volatile and persistent boundary chips tracegen,
- Added merkle chip tracegen as described [here](https://docs.google.com/document/d/12cH7ZYRFWHgflpPzOILb7bg5XExdyWOL4vwrQ9HFGkQ/edit?tab=t.0#heading=h.hrg0oexxgu9). To improve:
* Parallelize at least something,
* Maybe support passing this struct between segments.
- `VmChipTestBuilder` now has `::default_persistent`, so all tests in `extensions/rv32im/circuit` pass both with volatile and persistent memory interface.
> feat: memory access adapters, boundary chips, merkle chip E3

- Cargo.lock
- extensions/bigint/circuit/src/tests.rs
- extensions/rv32im/circuit/src/divrem/core.rs
- extensions/rv32im/circuit/src/mulh/core.rs
`cargo` complains that `uuid` has a conflict checksum.
> fix: Cargo lock & format

- crates/vm/src/system/memory/online.rs
- extensions/rv32im/circuit/src/base_alu/tests.rs
I used to handle creating new blocks in a wrong way when `align > initial_block_size`, now I hopefully do it right.
Also added persistent base alu tests, although nothing changed for the persistent case,
and added a dummy access in all of them that used to fail.
> fix: new block initialization in memory access adapters

- crates/vm/src/arch/execution_control.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/vm.rs
This resolves INT-4012 by not using memory controller's memory in E1 execution.
> feat: new execution remove redundant controller memory e1

- crates/cli/src/commands/build.rs
- crates/cli/src/commands/keygen.rs
- crates/cli/src/commands/prove.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/default.rs
- crates/cli/src/util.rs
- crates/cli/tests/build.rs
- crates/sdk/src/commit.rs
- crates/sdk/src/fs.rs
- `cargo openvm setup` supports skipping halo2 proving keys.
- `cargo openvm setup` outputs halo2 PK and stark PK as separated files.
- `cargo openvm build` outputs `AppExecutionCommit` in json. The old output(`exe_commit.bytes`) was incorrect.
close INT-3950
> refactor: CLI Build & Setup

- crates/sdk/src/fs.rs
Fixes the path from which verifier contract is read.
I tested the full CI flow on an aws instance to double check everything is working.
> fix: verifier read dir

- crates/toolchain/platform/src/aligned_buf.rs
- crates/toolchain/platform/src/alloc.rs
- crates/toolchain/platform/src/lib.rs
- extensions/keccak256/circuit/src/lib.rs
- extensions/keccak256/guest/src/lib.rs
- extensions/sha256/circuit/src/sha256_chip/mod.rs
- extensions/sha256/guest/src/lib.rs
Fixes misaligned accesses to sha256. Moved Aligned_buf to openvm platform so both `sha2` and `keccak` can access it
> fix: misaligned accesses to sha256

- crates/vm/src/system/memory/controller/mod.rs
We sometimes call `set_initial_memory` even with `Volatile` interface chip. Don't know if this alone is a good design, but inside this function we reset the tracing memory to use 8 as `initial_block_size` and then checked that in the volatile case the memory is empty, but the initial block size was already overwritten. This change fixes it.
> fix: Fix setting initial memory

- Cargo.lock
- Cargo.toml
- crates/vm/Cargo.toml
- crates/vm/src/arch/integration_api.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/offline_checker/columns.rs
- crates/vm/src/system/memory/offline_checker/mod.rs
- crates/vm/src/system/native_adapter/mod.rs
- crates/vm/src/system/public_values/core.rs
- crates/vm/src/system/public_values/mod.rs
- extensions/rv32im/circuit/Cargo.toml
- extensions/rv32im/circuit/src/adapters/alu.rs
- extensions/rv32im/circuit/src/adapters/mod.rs
- extensions/rv32im/circuit/src/auipc/core.rs
- extensions/rv32im/circuit/src/base_alu/core.rs
- extensions/rv32im/circuit/src/base_alu/mod.rs
This is targeting a new branch `feat/new-execution-e4` which we should merge into `feat/new-execution` only after we get everything compiling again. 
Review this only after all E1/2/3 tasks are resolved and "E4" becomes a blocker.
This PR introduces the traits necessary to unify E3 and what we were formerly calling E4 into a single E3 generic over a new concept of `RecordArena`. Basically `RecordArena` is a virtual allocator for records, which is backed by either the `RowMajorMatrix` itself or a more compact raw byte buffer (the latter is for hardware acceleration purposes).
As discussed offline, the `NewVmChipWrapper` struct no longer makes sense and we should move `RecordArena` parts into `CTX`. For now I made do by making some traits specific to RowMajorMatrix-backed arenas -- these …
> feat: traits for generalized E3

- crates/sdk/src/prover/vm/local.rs
- crates/vm/src/arch/execution_control.rs
- crates/vm/src/arch/execution_mode/e1.rs
- crates/vm/src/arch/execution_mode/metered/bounded.rs
- crates/vm/src/arch/execution_mode/metered/mod.rs
- crates/vm/src/arch/execution_mode/tracegen/mod.rs
- crates/vm/src/arch/execution_mode/tracegen/normal.rs
- crates/vm/src/arch/execution_mode/tracegen/segmentation.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/mod.rs
- crates/vm/src/arch/pure_execution.rs
- crates/vm/src/arch/vm.rs
- crates/vm/tests/integration_test.rs
- Add `InterpretedInstance` for E1/E2.
- Enforce `ExecutionControl` to be stateless.
- `InterpretedInstance` E2 is not tested because context initialization is tricky. Will address in the future PR.
close INT-4043
> refactor: VM Executor for E1/E2

- Cargo.lock
- crates/cli/src/commands/commit.rs
- crates/cli/src/commands/prove.rs
- crates/cli/src/commands/verify.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/codec.rs
- crates/sdk/src/commit.rs
- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/types.rs
- crates/sdk/tests/integration_test.rs
- guest-libs/verify_stark/guest/tests/integration_test.rs
Resolves INT-3880 and INT-4073. Implements the following:
- All CLI commit outputs are in hex
- `cargo openvm prove stark` outputs a JSON similar to `cargo openvm prove evm`
- Updates STARK verification to check app executable and VM commits
`cargo openvm prove stark` output looks like this:
```
{
"app_exe_commit": "004807b0289c7eeaa279e610af936bec5fa6f677d4f2da64bb53f39d37debe3c",
"app_vm_commit": "00249a27204ce75ed124a9cc45a722cab52744d57400c6967901260e5a510cd2",
"user_public_values": "200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"proof": "0100000002000..."
}
```
> feat: ensure all CLI commit outputs are in hex + fix verify STARK

- crates/vm/src/arch/execution_mode/metered/exact.rs
- crates/vm/src/arch/execution_mode/metered/mod.rs
- extensions/rv32im/circuit/src/extension.rs
- use unpadded height when calculating max height and total cells during segmentation
- use default segmentation thresholds from reth benchmark
> fix(new-execution): use unpadded height for segmentation

- crates/vm/src/arch/execution_mode/metered/mod.rs
- crates/vm/src/arch/vm.rs
- also increased the max trace cells threshold to 2bn for now
> fix(new-execution): return segments in `execute_metered`

- Cargo.lock
- Cargo.toml
- README.md
- book/src/getting-started/install.md
- book/src/introduction.md
- book/src/writing-apps/solidity.md
- extensions/native/recursion/src/fri/mod.rs
- extensions/native/recursion/src/fri/two_adic_pcs.rs
Updating the recursive verifier to match with the fix in https://github.com/Plonky3/Plonky3/security/advisories/GHSA-f69f-5fx9-w9r9
plonky3 has changed so that `proof.final_poly.len()` must equal
`config.final_poly_len()`. Since our recursion program only supports
final poly length = 0, we can remove the previous checks that higher
degree coefficients are zero.
The folding needs to add `beta^2` to roll in new terms from reduced
opening.
We introduce a new array `betas_squared` to precompute and cache the
squares since the `betas` are re-used across different FRI queries.
(Side note on optimization: Zach and I discussed and it seemed like
there is no difference between iter_zip'ing two arrays and loading them
both versus storing a pair in one array since we load each Ext as a
separate …
> fix(recursion): final_poly & FRI missing randomness

- extensions/ecc/guest/src/weierstrass.rs
For some reason, the cycle count on ecrecover benchmark halves when the `Group::is_identity` default implementation is overridden (even when overridden with the same code as the default implementation). My guess is the compiler refuses to inline the default implementation for some reason.
> feat: optimize `Group::is_identity`

- crates/vm/src/system/memory/merkle/mod.rs
- crates/vm/src/system/memory/merkle/tree.rs
Reth 21000000 tracegen [8.5](https://github.com/axiom-crypto/openvm-reth-benchmark/blob/gh-pages/benchmarks-dispatch/refs/heads/main/reth-b0d199966a0fb8aa4291bb898eb0ff7e1e721e75-fed5988df0993a3c5d0456cee0859ea17aacab67004fa00ee1a04f807143bb1a.md) -> [7.4](https://github.com/axiom-crypto/openvm-reth-benchmark/blob/gh-pages/benchmarks-dispatch/refs/heads/main/reth-33b8740cda3bb42b88c936c1b3ffa31e174c022b-dd1b108a50ec92cb6c91ff4b8e25fa58a5cd4628f28487650c8f9774eef505d1.md)
> feat: Do not build a `BTreeMap` when we don't need to

- extensions/ecc/guest/src/weierstrass.rs
A recent PR (#1709) introduced the optimization of overriding the default implementation of `Group::is_identity` in the `impl_sw_group_ops` macro. The overridden implementation was identical to the default one. This PR adds a comment to explain the code duplication.
> docs: Add comment explaining the `is_identity` optimization

- extensions/native/circuit/src/fri/mod.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/hintstore/mod.rs
- extensions/rv32im/circuit/src/load_sign_extend/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
This replaces this [PR](https://github.com/openvm-org/openvm/pull/1739)
I have been using execute_e1 in metered_execution in most places, but after an offline discussion with @shuklaayush  realized that memory accesses in e2 should be exactly the same as in e3. This PR fixes it for loadstore and hintstore. Fixed e2 keccak and sha2 in corresponding branches since they haven't been merged yet. I believe all other places should be correct.
Resolves INT-4204
> fix: memory accesses in metered execution should match exactly the memory accesses in `e3`

- crates/circuits/mod-builder/src/core_chip.rs
- crates/vm/src/system/memory/offline_checker/columns.rs
- crates/vm/src/system/native_adapter/util.rs
- extensions/native/circuit/src/extension.rs
- extensions/native/circuit/src/fri/mod.rs
- extensions/native/circuit/src/lib.rs
- extensions/native/circuit/src/loadstore/core.rs
- extensions/native/circuit/src/loadstore/tests.rs
- extensions/native/circuit/src/poseidon2/chip.rs
- extensions/native/circuit/src/poseidon2/mod.rs
Rewrite Native Poseidon2 chip for E4. The implementation follows the existing logic(directly writing into trace buffer) instead of creating a new minimal record struct. Rationale:
1. Simpler.
2. I also think poseidon2 columns computation is the bottleneck so a new minimal record struct won't help too much,
3. Each row can run in parallel.
close INT-4101
> feat: Poseidon2 E4

- crates/vm/src/system/memory/merkle/mod.rs
For each address space, find where the last nonzero value is and only use that prefix in `memory_to_vec_partition`
> feat: better merkle building

- crates/vm/src/arch/integration_api.rs
Added a method called `allocated` to be used in axiom-gpu
Removed unnecessary trait requirements for metadata when implementing `DenseRecordArena::alloc`.
> chore: add 'allocated' method to DenseRecordArena

- extensions/native/circuit/src/poseidon2/chip.rs
Otherwise memory is not metered properly
> fix: proper memory access functions in `execute_e1_impl` in the native poseidon chip

- Cargo.lock
- crates/toolchain/openvm/Cargo.toml
- crates/toolchain/openvm/src/getrandom.rs
- extensions/rv32im/tests/programs/Cargo.toml
- extensions/rv32im/tests/programs/examples/getrandom_v02.rs
- extensions/rv32im/tests/src/lib.rs
With the v1.3.0-rc release, we moved to supporting `getrandom v0.3`. However some libraries like `ecdsa` still use `getrandom v0.2` and it would give the unsupported backend error.
Turns out it is possible to support both simultaneously.
Closes INT-4187
> feat(toolchain): support `getrandom` v0.2 and v0.3 simultaneously

- .github/workflows/benchmarks-execute.yml
- enable codspeed instrumentation workflow on push. walltime seems unreliable so it's better to track instrumentation too. instrumentation takes time so it's still disabled for prs
> ci(new-execution): run codspeed instrumentation on push

- .github/workflows/cli.yml
- .github/workflows/extension-tests.yml
- .github/workflows/guest-lib-tests.yml
- .github/workflows/riscv.yml
- .github/workflows/sdk.yml
- crates/toolchain/openvm/Cargo.toml
- crates/toolchain/openvm/src/getrandom.rs
For reasons I am not entirely clear on, when you use `getrandom_v02::Error`, the `getrandom` crate pulls in `std` library. But if you just directly implement what the `register_custom_getrandom!` macro does, this goes away...
Fixes CI failure.
Full disclosure: I got the idea from https://github.com/risc0/risc0/pull/3106/files#diff-fd010fc66ba8d918981d2705c0d10cd65d19db599969bb29bb14caffa62d3b65R95
> fix: `getrandom` pulling in `std`

- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/memory_ctx.rs
- crates/vm/src/arch/vm.rs
@Golovanov399 pointed out that the `adapter_offset` was being calculated incorrectly. i did a couple of things in this pr:
- fixed `adapter_offset` and index finding logic
- added a `debug_assert` to verify that the calculated indices are correct
> fix(new-execution): adapter offset should be boundary_idx + 1

- extensions/native/circuit/src/poseidon2/chip.rs
Resolves INT-4288.
Discussed with @arayikhalatyan, for trace generation purposes we can actually treat native Poseidon2 as if it uses fixed-size records. This simplifies the GPU tracegen and allows us to not send any auxiliary information to the GPU device.
> feat: extract_layout implementation for native Poseidon2

- docs/specs/ISA.md
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
- update isa spec to specify that loads are only allowed from address space 2
- update isa spec to specify that the maximum valid pointer value in address space 1 is 127
- add a `debug_assert` that load address space is not 1 in loadstore instructions
Towards INT-4237
> fix(new-execution): disable loads from address space 1

- book/src/custom-extensions/algebra.md
- book/src/custom-extensions/ecc.md
- book/src/custom-extensions/overview.md
- book/src/custom-extensions/pairing.md
- book/src/guest-libs/pairing.md
- book/src/writing-apps/write-program.md
And update on support for both getrandom v0.2 and v0.3.
closes INT-4186
> docs(book): add docs on `init!` macro

- book/src/writing-apps/write-program.md
Clarify that OpenVM's use of the Harvard architecture and how it relates to reflective programming.
Closes INT-4352
> docs(book): clarify read-only reflection

- .github/workflows/cli.yml
- crates/cli/tests/app_e2e.rs
Currently if we change the workspace version before tagging, the integration test for `cargo openvm init` will break because it creates a guest crate that references the tagged version. I updated the test so it patches to the local openvm if the environmental variable `USE_LOCAL_OPENVM=1` is set.
> fix(test): use local `openvm` for testing `cargo openvm init`

- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/segment_ctx.rs
for metering, we assume all registers are going to be read during execution and don't add their contributions in the hot loop.
this pr fixes the `reset_segment` function to also add the register contributions
> fix(new-execution): add register contribtions on `reset_segment`

- crates/cli/tests/app_e2e.rs
The patching doesn't work because cargo still tries to fetch from git first before doing the patch, so instead we use a find replace approach. I have tested this with v1.4.0-rc.0 to ensure it works.
> fix(test): CLI init test patching not triggered

- benchmarks/execute/benches/execute.rs
- crates/sdk/src/keygen/dummy.rs
- crates/sdk/src/prover/root.rs
- crates/sdk/src/prover/vm/local.rs
- crates/sdk/tests/integration_test.rs
- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/public_values/core.rs
- crates/vm/src/utils/stark_utils.rs
- crates/vm/tests/integration_test.rs
- extensions/native/compiler/tests/public_values.rs
- extensions/rv32im/tests/src/lib.rs
- make `execute_with_metrics` a macro
- update `VmSegmentExecutor` `execute_metered` to use `InterpreterInstance`
- update `execute_metered` benchmarks
> feat(e12-fn-dispatch): make vm e2 use interpreter

- crates/vm/src/system/memory/adapter/mod.rs
- crates/vm/src/system/memory/adapter/records.rs
Towards INT-4117.
This makes some fields and functions more visible for the GPU to be able to use them.
> feat: Add pubs needed for gpu

- crates/vm/src/arch/integration_api.rs
added another utility function to `RecordSeeker` intended to be used by this axiom-gpu [PR](https://github.com/axiom-crypto/axiom-gpu/pull/124)
> feat: RecordSeeker::get_aligned_record_size

- crates/sdk/src/prover/agg.rs
The `verify_e2e_stark_proof` exists a fixed log blowup factor set by the internal proof. Therefore we must always generate an internal proof even if there is only 1 leaf proof.
Test run on a 1 segment proof: https://github.com/axiom-crypto/openvm-reth-benchmark/blob/gh-pages/benchmarks-dispatch/refs/heads/main/reth-c299bb2012ed6bf2aa289ee3decd45897c9ce574-59a742f87fe66d079554e6646f2a0fdabb1dc4d2e6afbf0f0b4f09376b854357.md
> fix(sdk): `aggregate_leaf_proofs` should always generate an internal proof

- crates/circuits/sha256-air/src/tests.rs
- crates/circuits/sha256-air/src/trace.rs
- extensions/sha256/circuit/src/sha256_chip/mod.rs
- extensions/sha256/circuit/src/sha256_chip/trace.rs
port `sha2` primitive tests to the new testbuilder
Renamed `Sha256StepHelper->Sha256FillerHelper`
> fix: sha2 primitive test

- crates/sdk/tests/integration_test.rs
- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/memory_ctx.rs
- crates/vm/src/arch/execution_mode/metered/segment_ctx.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/memory/online.rs
Changes:
- Increase the default segment check frequency from 100 to 1000.
- Postpone adapter height change to segment check instead of every memory access. There is still 1 adapter height update in `on_memory_operation` but postponing it will make benchmark slower.
Benchmarks: 
Codespeed and my local show significant performance gain. However, [reth-benchmark](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16380276462) doesn't have any change. I don't have a good explanation yet.
> chore: Optimize E2 Height Meter

- .github/workflows/guest-lib-tests.yml
- crates/sdk/guest/fib/src/main.rs
- guest-libs/verify_stark/tests/integration_test.rs
We hardcode these values in the `verify_stark` test
https://github.com/openvm-org/openvm/blob/af8f6c9037ac090d7148c3ba7056d7c9ef7d5f96/guest-libs/verify_stark/tests/integration_test.rs#L104-L108
Resolves INT-4429
> fix(new-execution): use smaller fib number in `verify_stark` test

- crates/toolchain/instructions/src/lib.rs
- crates/vm/src/system/native_adapter/mod.rs
- crates/vm/src/system/native_adapter/util.rs
- extensions/native/circuit/src/adapters/alu_native_adapter.rs
- extensions/native/circuit/src/adapters/branch_native_adapter.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
I went through the uses of `tracing_read` and switched to using constants for better compilation optimization whenever possible, where the requirements on the address space were determined according to ISA.md
I don't think there was really a performance diff: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16513213487
> chore(perf): use constant for address space in `tracing_read` when possible

- extensions/native/circuit/src/fri/mod.rs
The size of `a_prev_buf` (i.e. `a_prev_size`) was not being factored in the size calculation for `FriReducedOpeningRecordMut`, sometimes making the record too small.
> fix: native `FriReducedOpeningRecord` size calculation

- CHANGELOG.md
- crates/sdk/src/config/global.rs
- crates/vm/src/arch/config.rs
- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/testing/memory/mod.rs
- crates/vm/src/arch/testing/mod.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/memory/adapter/mod.rs
- crates/vm/src/system/memory/adapter/records.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/merkle/mod.rs
- crates/vm/src/system/memory/merkle/public_values.rs
- crates/vm/src/system/memory/merkle/trace.rs
- crates/vm/src/system/memory/mod.rs
- crates/vm/src/system/memory/offline_checker/bridge.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/persistent.rs
- crates/vm/src/system/mod.rs
- crates/vm/src/system/program/trace.rs
- crates/vm/src/utils/mod.rs
- crates/vm/src/utils/test_utils.rs
- extensions/native/circuit/src/utils.rs
- extensions/rv32im/circuit/src/adapters/alu.rs
- extensions/rv32im/circuit/src/loadstore/tests.rs
Add trait `AddressSpaceHostLayout` with concrete implementation as enum `MemoryCellType`.
Add `AddressSpaceHostConfig` struct and now `MemoryConfig` stores a vec of these, one per address space.
Now all handling of conversions from raw bytes to `F` is done through this config.
Comparison: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16532679208
Memory finalize time seems to have increased significantly percentage-wise, but it is still on the order of milliseconds so I think negligible?
> feat: add host configurable memory cell type to `MemoryConfig`

- crates/sdk/src/config/global.rs
`SdkVmConfigInner` is the more natural struct to work with, `SdkVmConfig` is just for serialization convenience.
> chore: make `SdkVmConfig::to_inner` pub

- benchmarks/execute/benches/execute.rs
- crates/sdk/src/config/global.rs
- extensions/pairing/circuit/src/config.rs
- extensions/pairing/circuit/src/pairing_extension.rs
`PairingProverExt` is backend agnostic because it is vacuous and the pairing extension only consists of phantom sub-executors.
Also changed a trait bound from `PrimeField32` to just `Field`
> chore: `PairingProverExt` is vacuous

- Cargo.lock
- Cargo.toml
- benchmarks/prove/Cargo.toml
- crates/sdk/Cargo.toml
- crates/vm/Cargo.toml
- crates/vm/src/arch/vm.rs
- crates/vm/src/utils/stark_utils.rs
Adds a new "stark-debug" feature to `openvm-circuit` and `openvm-sdk` for debugging purposes: when turned on, we pay a performance penalty to run the stark-backend debugger on all trace matrices before generating the proof. The debugger checks the constraints logically instead of cryptographically, which gives more information failure information.
Also updated stark-backend to tag `v1.2.0-rc.1` which updates to make logs at info level a little less verbose.
> feat: add "stark-debug" feature

- benchmarks/execute/benches/execute.rs
- benchmarks/prove/src/bin/kitchen_sink.rs
should fix ci in `feat/new-execution`
> fix(new-execution): fetch segments properly in kitchen_sink

- extensions/native/circuit/src/lib.rs
- extensions/native/circuit/src/poseidon2/chip.rs
Add a flag to execute E3 optimistically. When the flag is enabled, `verify_batch` skips all verification logic and postpone all poseidon2 hash computation to the tracegen phase.
[Reth-benchmark](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16510370163) shows 20% execution time reduction. Tracegen time slightly increases but the increment is less than the saving.
Close INT-4374
Per opcode stats on my laptop(variance is large but we could see a significant difference):
Before:
GROUP | FREQUENCY | TOTAL EXEC TIME | AVG TIME | Percentage
-- | -- | -- | -- | --
ADD | 599175 | 46411254 | 77.46 | 9.30%
BBE4DIV | 19534 | 7959238 | 407.46 | 1.60%
BBE4MUL | 52005 | 9243036 | 177.73 | 1.85%
COMP_POS2 | 27 | 53917 | 1,996.93 | 0.01%
DIV | 2184 | 390832 | 178.95 | 0.08%
FE4ADD | …
> chore: Optimistic E3 Execution for Poseidon2 Chip

- crates/vm/src/arch/record_arena.rs
- crates/vm/src/system/memory/online.rs
The function is confusing and easy to misuse because it includes the initial offset bytes which are only for alignment correct purposes.
> chore: remove `DenseRecordArena::current_size`

- benchmarks/execute/benches/execute.rs
- crates/sdk/src/keygen/dummy.rs
- crates/sdk/src/lib.rs
- crates/toolchain/tests/tests/riscv_test_vectors.rs
- crates/toolchain/tests/tests/transpiler_tests.rs
- crates/vm/src/arch/execution.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/phantom/execution.rs
- crates/vm/src/system/phantom/mod.rs
- crates/vm/src/utils/stark_utils.rs
- crates/vm/tests/integration_test.rs
- extensions/algebra/circuit/src/lib.rs
- extensions/ecc/circuit/src/weierstrass_chip/add_ne.rs
- extensions/ecc/circuit/src/weierstrass_chip/double.rs
- extensions/native/circuit/src/field_arithmetic/core.rs
- extensions/native/circuit/src/jal_rangecheck/mod.rs
- extensions/native/circuit/src/utils.rs
- extensions/native/compiler/tests/arithmetic.rs
- extensions/rv32im/circuit/src/load_sign_extend/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
- extensions/rv32im/tests/src/lib.rs
For ultra-low latency, all data that can be pre-computed once the program binary is known should be held in `InterpretedInstance` and not re-computed on the fly. This PR does this and closes INT-4470
- `VmExecutor` is constructed once the VM config is known and holds all data that can be determined before given a program binary. (For execution this is only the executors)
- `InterpretedInstance` should be created once the program binary is known and holds all pre-computed buffers and function pointers, so that `execute` can focus on only runtime specific computations.
- Refactored so that the `InterpretedInstance` now provides the only `execute` and `execute_metered` functions, and `VmExecutor` only provides constructors for the `InterpretedInstance`, which is separated between pure (E1) …
> feat: `InterpretedInstance` holds pre-computed handlers

- ci/scripts/metric_unify/flamegraph.py
- crates/vm/src/arch/interpreter_preflight.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/metrics/mod.rs
- crates/vm/src/system/memory/adapter/mod.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/mod.rs
The per-instruction call to calculate memory access adapter heights is very slow because it iterates linearly through the entire adapter record. I changed it now to only do this at the end. The downside is that we won't be able to see the contribution to access adapters on a per-instruction basis, but this could be extracted more efficiently in a different way.
Proof it works: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16767319820
> fix(perf-metrics): perf instrumentation slow

- crates/vm/src/system/memory/online/paged_vec.rs
- crates/vm/src/utils/mod.rs
Made a utility function that allocates and initializes a slice of memory with Rust's `alloc_zeroed`. Let me know if there are other places that could use this utility function
> feat: Field zero initialization

- crates/cli/src/lib.rs
- crates/toolchain/build/src/lib.rs
Previously toolchain version was hardcoded to some version of rust 1.86 nightly.
Sometimes users may want to use custom version, e.g. for some newest nightly Rust feature. In my case, I needed this to compile guest program that depends on main branch of revm as it has 1.88 MSRV.
> feat: allow to override compiler's Rust toolchain

- crates/prof/src/aggregate.rs
- crates/prof/src/lib.rs
- crates/prof/src/summary.rs
- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/interpreter_preflight.rs
- crates/vm/src/arch/record_arena.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/memory/merkle/trace.rs
- crates/vm/src/system/memory/persistent.rs
- crates/vm/src/system/memory/volatile/mod.rs
- docs/crates/metrics.md
- rename `execute_e3_time_ms` to `execute_preflight_time_ms` and now it includes `memory_finalize_time_ms`.
- the `single_trace_gen` info spans are skipped if record is empty just to reduce log verbosity
> chore: cleanup metrics

- crates/vm/src/system/memory/online.rs
This resolves INT-4549.
The assertion was a sanity check and it essentially checked that the "type size" should be greater than one. I replaced it with an `debug_assert_eq!(align, min block size from config)`.
While we are there, I also replaced some `cell_size` being `size_of::<T>()` or 1 with another value from config.
> chore: remove an old `assert!(address_space < NATIVE_AS)`

- Cargo.lock
Addresses the following warning:
```
warning: package `alloy-eips v1.0.20` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `alloy-serde v1.0.20` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
> chore: update Cargo.lock for alloy-eips v1.0.24

- Cargo.lock
- Cargo.toml
- benchmarks/prove/src/bin/kitchen_sink.rs
- crates/vm/Cargo.toml
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/state.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/online/memmap.rs
- crates/vm/src/system/program/trace.rs
Commit 61ba7ae5b8f68cc18dcf53e91fff7fec65cc6367 seemed to introduce a perf degradation because `fill_zero` is slower than the previous creation of a new memmap region. I think this is because memmap will just tell OS to give it new pages that are zero'd on-demand. I do this now for memmap memory by using `madvise` directly.
Comparison run between 61ba7ae5b8f68cc18dcf53e91fff7fec65cc6367 and this PR:  https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16925643699
- benchmark itself had a lot of noise, but if you search `vm.reset_state` in detailed metrics
- before: https://github.com/axiom-crypto/openvm-reth-benchmark/blob/gh-pages/benchmarks-dispatch/refs/heads/feat/new-execution/reth-30741fbba178d13d7a082dbe9668711e5aa37816-c4f412ba8d28ece7c9e686eb02c6ad77bd15fb42a3240326a …
> perf: `AddressMap` with `memmap` use madvise for zeroing

- benchmarks/execute/benches/execute.rs
- crates/vm/src/arch/config.rs
- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/memory_ctx.rs
- crates/vm/src/arch/execution_mode/metered/segment_ctx.rs
- crates/vm/src/arch/execution_mode/metered_cost.rs
- crates/vm/src/arch/execution_mode/mod.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/vm.rs
- crates/vm/tests/integration_test.rs
- add a `max_execution_cost` config parameter that determines the threshold up to which `execute_metered_cost` will execute
Resolves INT-4727
> feat(new-execution): halt on cost going above threshold

- crates/vm/src/arch/record_arena.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/online/paged_vec.rs
Compare bench with `feat/new-execution`: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17013157022
> perf: unroll fast path of `prev_access_time` and reduce duplicate work

- benchmarks/prove/src/bin/verify_fibair.rs
- benchmarks/prove/src/util.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/prover/agg.rs
- crates/sdk/src/prover/app.rs
- crates/sdk/src/util.rs
- crates/vm/src/arch/vm.rs
- emit a warning if `max_constraint_degree` don't matching between `VmConfig` and `StarkFriConfig`
> fix(new-execution): warn if `max_constraint_degree` differ

- crates/vm/src/arch/config.rs
- crates/vm/src/system/memory/online.rs
- extensions/native/circuit/src/fri/mod.rs
- extensions/native/circuit/src/fri/tests.rs
- Fixes various bugs in `batch_prev_access_times`.
- switched FriReducedOpening execute to use `batch_prev_access_times` which parallelizes some tracing memory operations.
On a 8 vCPU machine it doesn't make a difference / might be slightly worse.
Comparison benchmark (in progress): https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17028396319 
~~The next optimization is to do the actual reduced opening RLC using a parallel scan algorithm.~~ this was worse due to the thread switching overhead: https://github.com/openvm-org/openvm/pull/1992
> feat: FriReducedOpening with `batch_prev_access_times`

- .github/workflows/benchmarks-execute.yml
- .github/workflows/benchmarks.yml
- .github/workflows/build.yml
- .github/workflows/cli.yml
- .github/workflows/docs.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/extension-tests.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/guest-lib-tests.yml
- .github/workflows/lints.yml
- .github/workflows/merge-queue-controller.yml
- .github/workflows/native-compiler.yml
- .github/workflows/primitives.yml
- .github/workflows/recursion.yml
- .github/workflows/riscv.yml
- .github/workflows/sdk.yml
- .github/workflows/vm.yml
`github.workflow` refers to the caller's workflow name, so merge queue controller messes up all the concurrency of callee jobs.
context: https://stackoverflow.com/questions/79511940/using-workflow-filename-in-concurrency-group-for-workflows-started-by-workflow-c
if reviewers have better ideas how to handle merge queue with required status checks, I'm all ears
> ci: fix merge queue concurrency

- .github/merge-queue.yml
- .github/runs-on.yml
- .github/workflows/benchmark-call.yml
- .github/workflows/benchmarks-execute.yml
- .github/workflows/benchmarks-upload-fixtures.yml
- .github/workflows/benchmarks.yml
- .github/workflows/build.yml
- .github/workflows/cli.yml
- .github/workflows/docs.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/extension-tests.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/guest-lib-tests.yml
- .github/workflows/lints.yml
- .github/workflows/merge-queue-controller.yml
- .github/workflows/native-compiler.yml
- .github/workflows/pr-title.yml
- .github/workflows/primitives.yml
- .github/workflows/recursion.yml
- .github/workflows/riscv.yml
- .github/workflows/sdk.yml
- .github/workflows/versioning.yml
- .github/workflows/vm.yml
RunsOn recommends single label syntax now. Attempting to address runner stealing.
> ci(runs-on): use single label syntax

- .github/workflows/base-tests.cuda.yml
- .github/workflows/benchmarks-execute.yml
- .github/workflows/benchmarks.yml
- .github/workflows/build.yml
- .github/workflows/cli.yml
- .github/workflows/docs.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/extension-tests.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/guest-lib-tests.yml
- .github/workflows/lints.yml
- .github/workflows/merge-queue-controller.yml
- .github/workflows/native-compiler.yml
- .github/workflows/primitives.yml
- .github/workflows/recursion.yml
- .github/workflows/riscv.yml
- .github/workflows/sdk.yml
The merge queue is unstable and blocking PR merges due to not all jobs completing from workflow API flakiness or runner flakiness.
We will go back to merging to main and running workflows on push to main for now.
Additionally, I consolidated the primitives, vm, recursion CUDA tests to one runner to save some runners (and possibly compile time).
> ci: remove merge-queue and consolidate CUDA base tests

- .github/runs-on.yml
- .github/workflows/benchmark-call.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/lints.yml
switching back to spot runners because our vCPU quota is higher for spot than on-demand
> ci: use spot gpu runners

- .github/workflows/riscv.yml
- .github/workflows/sdk.yml
The SDK tests are the slowest tests to run. This PR speeds them up by:
- splitting ignored vs non-ignored tests onto different runners
- using `--release` mode
> ci: speed up sdk test with workflow matrix

- crates/cli/Cargo.toml
- crates/sdk/Cargo.toml
- crates/vm/Cargo.toml
- crates/vm/src/arch/execution_mode/metered_cost.rs
- crates/vm/src/system/memory/online/memmap.rs
- add bounds checking for memory access in memmap unless `unprotected` feature is enabled (disabled by default)
[comparison benchmark](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17308694277)
> fix: explicit panic on oob memory access

- docs/vocs/docs/pages/book/writing-apps/overview.mdx
Noting that the example repo will be updated after merging https://github.com/openvm-org/openvm-example-fibonacci/pull/6 and https://github.com/openvm-org/openvm-example-fibonacci/pull/4.
Closes INT-4938
> chore: update input doc with an example

- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/segment_ctx.rs
Replace the optimistic execution/segmentation with a checkpointing approach that checkpoints the last `trace_height`/`instret` value that is below the thresholds and use these values for the segments. This should make the segmentation more predictable for downstream usage since the segments should satisfy the thresholds (with the only caveat being if segmentation happens when there is no checkpoint to fall back to i.e. if we overshoot the threshold before the first segmentation check) 
This requires storing some extra state and results in a higher segment count compared to earlier for the same thresholds. Also makes execution slightly slower since we're doing some extra work now
[benchmark run](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17750607194) with 0.7B max …
> fix: ensure segments are below thresholds

- crates/sdk/tests/integration_test.rs
- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/state.rs
- E2 execution supports suspension every segment. [Reth-benchmark](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17782856127) doesn't show performance difference.
- `VmExecState`/`VmState` supports clone. Benchmark shows cloning a VM state which only uses address space 2 takes 0.3~0.6ms.
closes INT-5066
closes INT-5067
> feat: E2 supports suspension & VmExecState supports clone

- Cargo.lock
- Cargo.toml
includes https://github.com/openvm-org/stark-backend/pull/131
> chore: bump stark-backend to `v1.2.1-rc.2`

- crates/vm/src/arch/execution.rs
- crates/vm/src/arch/interpreter.rs
`InterpretedInstance::execute_from_state` for pure execution was using `num_insns` instead of `instret_end` in the `ExecutionCtx` constructor. This was not caught because we currently only ever execute from `instret=0`.
> fix: execution from non-zero `instret`
