openvm-org/openvm

- ci/scripts/utils.sh
- docs/specs/circuit.md
- extensions/native/compiler/Cargo.toml
- extensions/pairing/circuit/src/pairing_chip/miller_double_step.rs
> chore: fix links and comments

- crates/toolchain/build/src/lib.rs
Added constants for environment variable names to improve maintainability and prevent typos
> refactor(toolchain): consolidate env vars and cleanup code

- extensions/rv32-adapters/src/eq_mod.rs
- extensions/rv32-adapters/src/heap.rs
- extensions/rv32-adapters/src/heap_branch.rs
- extensions/rv32-adapters/src/vec_heap.rs
- extensions/rv32-adapters/src/vec_heap_two_reads.rs
- extensions/rv32im/circuit/src/adapters/alu.rs
- extensions/rv32im/circuit/src/adapters/branch.rs
- extensions/rv32im/circuit/src/adapters/hintstore.rs
- extensions/rv32im/circuit/src/adapters/jalr.rs
- extensions/rv32im/circuit/src/adapters/loadstore.rs
- extensions/rv32im/circuit/src/adapters/mul.rs
- extensions/rv32im/circuit/src/adapters/rdwrite.rs
- extensions/rv32im/circuit/src/branch_lt/core.rs
- extensions/rv32im/circuit/src/jal_lui/core.rs
- extensions/rv32im/circuit/src/jalr/core.rs
> chore: replace 4 with `DEFAULT_PC_STEP`

- crates/vm/src/arch/testing/mod.rs
- crates/vm/src/system/memory/controller/interface.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/mod.rs
- crates/vm/src/system/memory/offline.rs
- crates/vm/src/system/memory/online.rs
- crates/vm/src/system/memory/persistent.rs
- crates/vm/src/system/memory/tree/public_values.rs
- crates/vm/src/system/native_adapter/mod.rs
- extensions/native/circuit/src/poseidon2/mod.rs
* Move OfflineMemory into separate module
* Delete unused Memory(Read|Write)Record
> refactor: OfflineMemory

- docs/crates/benchmarks.md
Fix typo in benchmarks.md
This pull request addresses a small typo in the `benchmarks.md` file to enhance the documentation's clarity and precision.
- Corrected a minor typographical error in the text.
---
If there are further improvements or adjustments needed, feel free to suggest them. Thank you!
> fix typo Update benchmarks.md

- Cargo.lock
- Cargo.toml
- benchmarks/src/bin/verify_fibair.rs
- crates/vm/src/arch/integration_api.rs
sync with https://github.com/openvm-org/stark-backend/pull/19
**Changed verify_fibair benchmark to n=2^15 for larger benchmark**
> feat: quotient polynomial evaluation from serialized constraints

- extensions/native/circuit/src/fri/mod.rs
It's hard to unit test `Stateful`. Fix this first and will think about how to test
> [fix] Stateful for FriReducedOpeningChip

- extensions/native/recursion/src/stark/mod.rs
> chore: remove TODO on phases since we only use 1 phase for now

- crates/sdk/tests/integration_test.rs
- extensions/native/compiler/src/conversion/mod.rs
> chore: remove unused compiler options

- crates/vm/src/arch/vm.rs
Reverts openvm-org/openvm#1251
broke reth benchmark
> Revert "[feat] support execute until segment"

- crates/circuits/mod-builder/src/builder.rs
- crates/circuits/mod-builder/src/core_chip.rs
- extensions/ecc/circuit/src/weierstrass_chip/double.rs
- extensions/ecc/circuit/src/weierstrass_chip/mod.rs
- support checking more constants during setup
- support new finalization (with dummy row and temp range checker)
Closes INT-3087
> Updated mod-builder to support better setup and finalization

- examples/algebra/src/main.rs
Can I "Build and run book examples" now in this PR?
> [fix] algebra example after last complex macro fix

- Cargo.lock
- Cargo.toml
- crates/prof/src/aggregate.rs
to sync with https://github.com/openvm-org/stark-backend/pull/30
> perf: update `stark-backend` to v0.3.0

- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/vm.rs
- crates/vm/tests/integration_test.rs
- extensions/native/circuit/src/extension.rs
- extensions/native/compiler/src/lib.rs
> [feat] Add HintLoad phantom opcode

- .github/workflows/benchmarks.yml
- Cargo.lock
- Cargo.toml
- benchmarks/src/utils.rs
- crates/sdk/src/config/mod.rs
- crates/sdk/src/keygen/mod.rs
- crates/sdk/tests/integration_test.rs
Better interaction chunking strategy for FRI logup: https://github.com/openvm-org/stark-backend/pull/31
> perf: `stark-backend` v0.4 with better interaction chunking

- crates/circuits/mod-builder/src/README.md
The first two commits are from #1269 and they will be merged into main soon.
The important commit for this issue is the third one.
Closes INT-3089
> [docs] Add contributor documentation for the `mod-builder` framework

- Cargo.lock
- crates/sdk/src/keygen/mod.rs
- crates/sdk/src/keygen/perm.rs
- crates/sdk/src/verifier/common/mod.rs
- crates/sdk/src/verifier/leaf/vars.rs
- crates/vm/src/metrics/cycle_tracker/mod.rs
- extensions/ecc/guest/src/msm.rs
- extensions/native/compiler/src/constraints/halo2/compiler.rs
- extensions/native/compiler/tests/array.rs
- extensions/native/tests/programs/Cargo.toml
> chore: cleanup FIXMEs in code

- .github/workflows/benchmarks.yml
- Cargo.lock
- Cargo.toml
better interaction chunking https://github.com/openvm-org/stark-backend/pull/33
> chore: `stark-backend` v0.4.1

- benchmarks/src/utils.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/metrics/mod.rs
> fix: cycle tracker pass between segments

- crates/cli/Cargo.toml
- crates/vm/src/arch/extensions.rs
also re-export feature "bench-metrics" for cli
> chore: tracing log of cycle count

- crates/prof/src/aggregate.rs
- crates/prof/src/main.rs
- crates/prof/src/summary.rs
- crates/prof/src/types.rs
I tested locally it works with https://bencher.dev/docs/how-to/track-custom-benchmarks/
> feat(prof): add aggregate metric output in Bencher JSON format

- extensions/native/recursion/src/fri/hints.rs
- extensions/native/recursion/src/fri/types.rs
- extensions/native/recursion/src/hints.rs
> [chore] Add more cycle tracker for hint

- crates/vm/src/system/memory/paged_vec.rs
**Metric:** tracegen
**Before:** 10,956.73 ms
**After:** 10,673.18 ms
**Percentage gain:** -2.6%
Workflow: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/13162579475
---
Here we do some unsafe stuff similar to what we did in `range_array` when implementing pagevecs, but back then I somehow missed the same thing with vec-analogs of these functions.
> [perf] Make `set_range` and `range_vec` faster via `unsafe`

- Cargo.lock
- Cargo.toml
**Note:** Some vkey may change due to https://github.com/openvm-org/stark-backend/pull/43
> chore: update `stark-backend` rev

- crates/circuits/poseidon2-air/src/babybear.rs
@jonathanpwang superseeds https://github.com/openvm-org/openvm/pull/1361 to avoid some rebasing mess :)
> poseidon-air: simplify horizen_round_consts impl

- crates/vm/src/arch/extensions.rs
Followup of https://github.com/openvm-org/openvm/pull/1376
> chore: remove `VmChipComplexState`

- crates/circuits/mod-builder/src/README.md
- crates/circuits/mod-builder/src/field_variable.rs
- crates/circuits/mod-builder/src/symbolic_expr.rs
Added the spec to the README and added some comments
Authored by @Avaneesh-axiom
> spec: update spec for `mod-builder`

- crates/circuits/sha256-air/src/air.rs
- crates/circuits/sha256-air/src/columns.rs
- crates/circuits/sha256-air/src/trace.rs
- extensions/sha256/circuit/README.md
- extensions/sha256/circuit/src/sha256_chip/air.rs
- extensions/sha256/circuit/src/sha256_chip/columns.rs
- Added SHA-256 VM extension spec document
- Improved comments throughout the code
Authored by @Avaneesh-axiom
> docs(spec): update SHA-2 VM extension spec

- Cargo.lock
- Cargo.toml
- crates/vm/src/arch/vm.rs
- extensions/native/recursion/src/config/outer.rs
- extensions/native/recursion/src/stark/mod.rs
- extensions/native/recursion/src/types.rs
Sync recursive verifiers with https://github.com/openvm-org/stark-backend/pull/54
Closes INT-3564
> fix: update stark-backend to protect against weak Fiat-Shamir

- benchmarks/programs/fibonacci/src/main.rs
- benchmarks/programs/regex/src/main.rs
- book/src/getting-started/quickstart.md
- book/src/writing-apps/write-program.md
- crates/toolchain/openvm/src/io/mod.rs
- extensions/rv32im/tests/programs/examples/reveal.rs
- extensions/rv32im/tests/src/lib.rs
> feat: add `reveal_bytes32` io function

- crates/vm/src/utils/stark_utils.rs
- extensions/pairing/tests/src/lib.rs
don't run debugger on pairing fallback
> test: speed up pairing test

- crates/vm/src/system/memory/controller/mod.rs
Missed a push in https://github.com/openvm-org/openvm/pull/1496/files
> chore(style): use log2_ceil

- Cargo.lock
- Cargo.toml
- extensions/native/recursion/src/stark/mod.rs
Sync with https://github.com/openvm-org/stark-backend/pull/56
> feat(recursion): observe AIR IDs in verifier

- crates/circuits/primitives/src/range_tuple/tests.rs
- try to pass ci
- not sure if this is what the earlier test was testing
> fix(test): update negative range tuple test

- .github/workflows/lints.yml
- Cargo.lock
- crates/toolchain/openvm/Cargo.toml
- crates/toolchain/platform/Cargo.toml
- extensions/ecc/guest/Cargo.toml
[`cargo shear`](https://github.com/Boshen/cargo-shear) checks for unused dependencies
should be merged after #1506
> feat(ci): add cargo shear lint

- book/src/advanced-usage/sdk.md
- book/src/writing-apps/write-program.md
> book: mention consistency between guest max memory and VM memory config

- book/src/SUMMARY.md
- book/src/writing-apps/prove.md
- book/src/writing-apps/verify.md
> book: update EVM proof format

- README.md
- SECURITY.md
- audits/v1-internal/README.md
- book/src/introduction.md
> feat: update security for v1 release

- book/src/custom-extensions/ecc.md
- book/src/custom-extensions/pairing.md
- book/src/introduction.md
> fix: Clarifications to book about ECC and Pairing extensions

- docs/specs/continuations.md
This resolves INT-3712.
This change adds details about different steps of the recursive proving from https://hackmd.io/RidB9Q7rRMSw9bjf4YHSLA.
> docs: add more details into the continuations spec

- .github/workflows/cli.yml
- Cargo.lock
- Cargo.toml
- crates/sdk/Cargo.toml
- crates/sdk/src/fs.rs
- crates/sdk/src/lib.rs
Adds `forge_fmt` to the verifier and alters folder structure to align with the intended publishing structure in `openvm-solidity-sdk` so that metadata hashes can match.
> feat: format verifier

- Cargo.lock
- Cargo.toml
> chore: bump `stark-backend` to `v1.0.1`

- audits/v1-internal/extension-algebra.md
- audits/v1-internal/extension-native.md
- audits/v1-internal/isa.md
I know you don't acknowledge PR's with minor typo fixes, 
But I found some typos that should be fixed, and they are not subjective or minor ones.
> fix: several typos of different importance

- .github/workflows/benchmarks-execute.yml
- Cargo.lock
- benchmarks/execute/Cargo.toml
> feat(new-execution): add codspeed execution benchmark

- .github/workflows/cli.yml
- examples/i256/src/main.rs
- examples/keccak/src/main.rs
- examples/u256/src/main.rs
> chore: add entry point to book examples without openvm::init!()

- book/src/writing-apps/prove.md
- crates/cli/src/bin/cargo-openvm.rs
- crates/cli/src/commands/commit.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/prove.rs
- crates/sdk/src/commit.rs
- crates/sdk/src/fs.rs
> feat: commit command for cargo openvm

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/bin/cargo-openvm.rs
- crates/cli/src/commands/init.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/util.rs
- crates/cli/templates/lib.rs
- crates/cli/templates/main.rs
- crates/cli/templates/openvm.toml
- crates/cli/tests/app_e2e.rs
- crates/toolchain/build/src/lib.rs
> feat: init command for cargo openvm

- Cargo.lock
- Cargo.toml
Bumped to v1.0.1 (same as main)
> chore: bump stark backend

- crates/vm/src/arch/execution_mode/metered/mod.rs
- extensions/algebra/circuit/src/modular_chip/is_eq.rs
- added a missing pc increment step in `ModularIsEqualStep`
> fix(new-execution): add missing pc increment

- crates/vm/src/arch/execution_mode/metered/mod.rs
- total cells = max_cells_per_chip * total_chips
> fix(new-execution): properly calculate total max cells

- docs/specs/ISA.md
- extensions/rv32im/circuit/src/divrem/core.rs
> docs: update division typo in ISA.md

- benchmarks/execute/src/main.rs
- crates/sdk/src/keygen/dummy.rs
- crates/sdk/src/prover/root.rs
- crates/sdk/src/prover/vm/local.rs
- crates/sdk/tests/integration_test.rs
- crates/vm/src/arch/execution_mode/metered/bounded.rs
- crates/vm/src/arch/execution_mode/metered/mod.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/connector/tests.rs
- crates/vm/tests/integration_test.rs
- extensions/native/compiler/tests/public_values.rs
cherrypick of #1763 to `feat/new-execution`
> fix(new-execution): prevent segmentation in single segment executor

- extensions/native/circuit/src/fri/mod.rs
- remove all redundant fields from the fri records
- reorder fields according to how they occur in the trace
> fix(new-execution): make fri record minimal

- .github/workflows/guest-lib-tests.yml
- Cargo.lock
Runs the `verify-stark` integration test in CI
> chore: run verify-stark tests in ci

- Cargo.lock
- Cargo.toml
- benchmarks/prove/src/util.rs
- crates/vm/Cargo.toml
- crates/vm/src/arch/extensions.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/system/memory/controller/mod.rs
- crates/vm/src/system/memory/merkle/trace.rs
- crates/vm/src/system/memory/persistent.rs
- crates/vm/src/system/memory/volatile/mod.rs
sync with https://github.com/openvm-org/stark-backend/pull/81
> chore: use tracing spans for metrics

- extensions/bigint/circuit/src/branch_eq.rs
- extensions/bigint/circuit/src/branch_lt.rs
- extensions/rv32im/circuit/src/divrem/core.rs
- extensions/rv32im/circuit/src/less_than/core.rs
- extensions/rv32im/circuit/src/loadstore/core.rs
- fixed some execute functions to match the spec. details in comments
> fix(execute-opt): misc fixes to rv32/bigint e1 execute

- Cargo.lock
- crates/vm/src/arch/extensions.rs
- crates/vm/src/system/mod.rs
- extensions/algebra/circuit/src/fp2_extension.rs
- extensions/algebra/circuit/src/modular_chip/is_eq.rs
- extensions/algebra/circuit/src/modular_chip/mod.rs
- extensions/algebra/circuit/src/modular_extension.rs
- extensions/bigint/circuit/src/extension.rs
- extensions/ecc/circuit/src/config.rs
- extensions/ecc/circuit/src/weierstrass_chip/add_ne.rs
- extensions/ecc/circuit/src/weierstrass_chip/double.rs
- extensions/ecc/circuit/src/weierstrass_chip/mod.rs
- extensions/ecc/circuit/src/weierstrass_extension.rs
- extensions/keccak256/circuit/src/extension.rs
- extensions/native/circuit/src/extension.rs
- extensions/pairing/circuit/src/config.rs
- extensions/pairing/circuit/src/pairing_extension.rs
- extensions/rv32im/circuit/src/extension.rs
- extensions/sha256/circuit/src/extension.rs
- guest-libs/k256/tests/lib.rs
- guest-libs/p256/tests/lib.rs
all the int tests compile and run now but some still fail: investigating that now
Also, fixed `pointer_max_bits` related TODOs, but there are still 3 TODOs let related to getting the `VariableRangeCheckerBus` from `ExecutorInventory`
update: all int tests pass now except `ruint`
> feat: new vm extension traits

- .github/workflows/versioning.yml
- CHANGELOG.md
- book/src/getting-started/install.md
- book/src/getting-started/quickstart.md
> chore: update book for v1.3.0 release

- extensions/sha256/circuit/src/sha256_chip/mod.rs
> feat: public sha2 trace

- .github/workflows/versioning.yml
Passing run: https://github.com/openvm-org/openvm/actions/runs/16460596310/job/46526942880
> fix(ci): install CLI with --locked

- CHANGELOG.md
- docs/specs/ISA.md
> fix(docs): update isa spec to specify alignment requirements

- extensions/pairing/guest/src/halo2curves_shims/bn254/final_exp.rs
- cache some constants in `final_exp_hint` calculation. they are still `static` for consistency but should ideally be `const`
- makes execution ~2x faster for [block 21897500](https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/16682033418)
Towards INT-4535
> perf(new-execution): cache constants in pairing `final_exp_hint`

- crates/vm/src/arch/execution_mode/tracegen.rs
- crates/vm/src/arch/interpreter.rs
- crates/vm/src/arch/segment.rs
- crates/vm/src/arch/vm.rs
- crates/vm/src/metrics/mod.rs
- crates/vm/src/system/phantom/execution.rs
- crates/vm/tests/integration_test.rs
> refactor(new-execution): make `VmSegmentState` a superset of `VmState`

- Cargo.lock
- Cargo.toml
This reverts commit 22f1a5b865ac9c7a4409488eda0db6f65c5ff2b6.
> fix(new-execution): revert "chore: update snark-verifier to v0.2.3 (#1938)"

- docs/vocs/docs/pages/book/advanced-usage/sdk.mdx
- docs/vocs/docs/pages/book/getting-started/install.mdx
- docs/vocs/docs/pages/book/getting-started/quickstart.mdx
- docs/vocs/docs/pages/book/writing-apps/generating-proofs.mdx
- docs/vocs/docs/pages/book/writing-apps/overview.mdx
- docs/vocs/docs/pages/book/writing-apps/solidity-sdk.mdx
- docs/vocs/docs/pages/book/writing-apps/verifying-proofs.mdx
- docs/vocs/docs/pages/index.mdx
> feat: add `--evm` flag for `cargo openvm setup` and bump versions

- docs/vocs/docs/pages/book/getting-started/install.mdx
- docs/vocs/docs/pages/index.mdx
Testing:
- Verified on clean Ubuntu install
- Verified on clean MacOS install with `xcode-select --install` already run
Closes INT-4585
> feat: add clean install prereqs for Ubuntu and Mac

- crates/cli/src/commands/setup.rs
> fix(cli): force regenerate STARK aggregation keys

- .github/runs-on.yml
> ci: update runson repository configuration

- crates/circuits/primitives/cuda/src/dummy/less_than.cu
- crates/circuits/primitives/src/cuda_abi.rs
- crates/circuits/sha256-air/cuda/include/tracegen.cuh
- extensions/native/circuit/cuda/src/branch_eq.cu
- extensions/native/circuit/cuda/src/castf.cu
- extensions/native/circuit/cuda/src/field_extension/field_extension.cu
- extensions/native/circuit/cuda/src/fri/fri.cu
- extensions/native/circuit/cuda/src/jal_rangecheck.cu
- extensions/native/circuit/cuda/src/poseidon2/kernels.cu
- extensions/native/circuit/src/branch_eq/cuda.rs
- extensions/native/circuit/src/castf/cuda.rs
- extensions/native/circuit/src/cuda_abi.rs
- extensions/native/circuit/src/field_extension/cuda.rs
- extensions/native/circuit/src/fri/cuda.rs
- extensions/native/circuit/src/jal_rangecheck/cuda.rs
- extensions/native/circuit/src/loadstore/cuda.rs
- extensions/native/circuit/src/poseidon2/cuda.rs
- extensions/rv32im/circuit/src/cuda_abi.rs
- extensions/rv32im/circuit/src/divrem/cuda.rs
- extensions/rv32im/circuit/src/hintstore/cuda.rs
- extensions/sha256/circuit/cuda/src/sha256.cu
- extensions/sha256/circuit/src/cuda_abi.rs
- extensions/sha256/circuit/src/sha256_chip/cuda.rs
> chore: Replace allegedly all `width`, `height` and `rows_used` types with `usize`

- crates/circuits/primitives/cuda/src/dummy/less_than.cu
- crates/circuits/primitives/src/cuda_abi.rs
- crates/circuits/sha256-air/cuda/include/tracegen.cuh
- extensions/native/circuit/cuda/src/branch_eq.cu
- extensions/native/circuit/cuda/src/castf.cu
- extensions/native/circuit/cuda/src/field_extension/field_extension.cu
- extensions/native/circuit/cuda/src/fri/fri.cu
- extensions/native/circuit/cuda/src/jal_rangecheck.cu
- extensions/native/circuit/cuda/src/poseidon2/kernels.cu
- extensions/native/circuit/src/branch_eq/cuda.rs
- extensions/native/circuit/src/castf/cuda.rs
- extensions/native/circuit/src/cuda_abi.rs
- extensions/native/circuit/src/field_extension/cuda.rs
- extensions/native/circuit/src/fri/cuda.rs
- extensions/native/circuit/src/jal_rangecheck/cuda.rs
- extensions/native/circuit/src/loadstore/cuda.rs
- extensions/native/circuit/src/poseidon2/cuda.rs
- extensions/rv32im/circuit/src/cuda_abi.rs
- extensions/rv32im/circuit/src/divrem/cuda.rs
- extensions/rv32im/circuit/src/hintstore/cuda.rs
- extensions/sha256/circuit/cuda/src/sha256.cu
- extensions/sha256/circuit/src/cuda_abi.rs
- extensions/sha256/circuit/src/sha256_chip/cuda.rs
rebase of https://github.com/openvm-org/openvm/pull/2050
> chore: replace all `width, height, rows_used` types with `usize`

- .github/workflows/extension-tests.cuda.yml
- extensions/bigint/circuit/Cargo.toml
- extensions/keccak256/circuit/Cargo.toml
- extensions/native/circuit/Cargo.toml
- extensions/pairing/circuit/Cargo.toml
- extensions/rv32im/circuit/Cargo.toml
- extensions/sha256/circuit/Cargo.toml
> chore: Add the touchemall feature to extension tests

- .github/workflows/benchmark-call.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/lints.yml
- .github/workflows/riscv.yml
- Cargo.toml
- ci/scripts/bench.py
sync with 
- https://github.com/openvm-org/stark-backend/pull/103
- https://github.com/openvm-org/stark-backend/pull/104
- https://github.com/openvm-org/stark-backend/pull/105
> chore: bump stark-backend with CUDA compatibility with target-cpu=native

- docs/vocs/docs/pages/specs/security/audits.mdx
- docs/vocs/docs/pages/specs/security/reporting-vulnerabilities.mdx
- docs/vocs/docs/pages/specs/security/security-model.mdx
- docs/vocs/sidebar.ts
> docs: add new security section

- .github/workflows/benchmark-call.yml
- .github/workflows/benchmarks.yml
Try to prevent runner stealing
> ci(benchmarks): add job index

- crates/cli/src/input.rs
- docs/vocs/docs/pages/book/writing-apps/overview.mdx
- docs/vocs/docs/pages/book/writing-apps/running-a-program.mdx
This resolves INT-4892.
This change also puts hex string validation and decoding into one function
> chore: mention even hex message in cargo cli

- docs/README.md
- docs/contributor-setup.md
- docs/repo/README.md
- docs/repo/cuda.md
> docs: CUDA and non-CUDA contributor setup doc

- docs/vocs/docs/pages/book/acceleration-using-extensions/elliptic-curve-cryptography.mdx
> docs: use P256Point instead of P256Affine in book

- docs/crates/vm.md
- add execution section
- update outdated sections
Resolves INT-4885
> docs: update VM crate documentation 

- docs/vocs/docs/pages/book/getting-started/introduction.mdx
> fix: update about this book section

- crates/cli/src/commands/verify.rs
- crates/cli/src/util.rs
- docs/vocs/docs/pages/book/writing-apps/verifying-proofs.mdx
> feat: remove unnecessary run options from cargo openvm verify stark

- .github/workflows/docs.yml
> ci: build docs with cuda feature

- .github/workflows/base-tests.cuda.yml
- .github/workflows/extension-tests.cuda.yml
- .github/workflows/extension-tests.yml
- .github/workflows/guest-lib-tests.cuda.yml
- .github/workflows/guest-lib-tests.yml
- .github/workflows/riscv.yml
- .github/workflows/vm.yml
- crates/vm/src/utils/stark_utils.rs
> ci: skip debug during CI air test

- crates/vm/cuda/src/system/poseidon2.cu
- crates/vm/src/cuda_abi.rs
- crates/vm/src/system/cuda/poseidon2.rs
don't use cudaMalloc inside of the kernel launcher and use memory manager
> chore(cuda): update poseidon2 kernel to use memory manager

- crates/vm/src/arch/execution_mode/metered/ctx.rs
- crates/vm/src/arch/execution_mode/metered/segment_ctx.rs
- log total cells, total interactions and max trace height for each segment
> fix: log more information for segments
